package web

import "github.com/SampsonFox/assetloop/internal/application"

func init() {
	for k, v := range map[string]string{"market.search": "搜索二手物品", "market.title": "二手行情", "market.reference": "二手参考价", "market.zhuanzhuan": "转转", "market.name": "名称", "market.keyword": "型号关键词", "market.filter": "配置条件（如 256GB）", "market.model": "匹配型号", "market.observed": "获取时间", "market.help": "同款设备可共享行情，每日保存最新成交参考价。", "market.shared": "显式选择同款配置，两台设备可以共用一份行情。", "market.create": "添加二手物品", "market.unbound": "暂不绑定", "market.empty": "暂无二手价格", "market.no_items": "暂无二手物品，添加后可在物品编辑中绑定。", "market.basis": "转转最新一期成交最高价", "market.refresh": "刷新价格", "market.preview": "查询预览", "market.confirm": "确认型号并保存", "market.query_again": "重新查询", "market.immutable": "查询配置固定；如需更换型号或配置，请添加新的二手物品。", "market.authentication": "转转凭证无效或已过期，请检查本地配置。", "market.rate_limit": "接口限流，请稍后重试。", "market.temporary": "暂时无法获取行情，原价格已保留。", "market.invalid_response": "接口未返回有效价格，原价格已保留。", "market.unconfigured": "尚未配置转转凭证。请在本地环境配置中设置令牌。", "market.model_changed": "接口匹配型号发生变化，请核对查询配置，原价格已保留。", "market.busy": "正在刷新或已停用，请稍后查看。", "market.fx_pending": "汇率待获取，当前显示原币价格。", "market.failed": "未能完成操作，请检查输入或稍后重试。"} {
		messages[application.LocaleZhCN][k] = v
	}
	for k, v := range map[string]string{"market.search": "Search market items", "market.title": "Secondhand prices", "market.reference": "Secondhand reference", "market.zhuanzhuan": "Zhuanzhuan", "market.name": "Name", "market.keyword": "Model keywords", "market.filter": "Configuration (e.g. 256GB)", "market.model": "Matched model", "market.observed": "Retrieved at", "market.help": "Share a quote between matching devices. Latest sale references are recorded daily.", "market.shared": "Select the matching configuration. Multiple devices can share one price series.", "market.create": "Add market item", "market.unbound": "No binding", "market.empty": "No secondhand price", "market.no_items": "No market items yet. Add one and bind it in an asset editor.", "market.basis": "Zhuanzhuan latest-period maximum sale price", "market.refresh": "Refresh price", "market.preview": "Preview quote", "market.confirm": "Confirm model and save", "market.query_again": "Query again", "market.immutable": "Query configuration is fixed. Add a new market item for a different model or configuration.", "market.authentication": "Zhuanzhuan credentials are invalid or expired. Check local configuration.", "market.rate_limit": "Rate limited. Retry later.", "market.temporary": "Quote temporarily unavailable. Previous price retained.", "market.invalid_response": "No valid quote returned. Previous price retained.", "market.unconfigured": "Zhuanzhuan is not configured. Set the token in local environment configuration.", "market.model_changed": "Matched model changed. Check the query; previous price retained.", "market.busy": "Refresh is running or the item is disabled. Check again later.", "market.fx_pending": "Exchange rate pending; showing the original quote currency.", "market.failed": "Operation failed. Check the input or retry later."} {
		messages[application.LocaleEn][k] = v
	}
}
