package web

import "github.com/SampsonFox/assetloop/internal/application"

func init() {
	for k, v := range map[string]string{"market.find_products": "搜索转转商品", "market.find_help": "搜索同款商品，查看规格后选择配置，再查询成交参考价。", "market.direct": "直接按型号查询", "market.use_product": "使用此商品配置", "market.asking": "在售价", "market.view_specs": "查看规格", "market.no_products": "没有找到商品，请调整关键词或直接按型号查询。", "market.not_provided": "未提供", "market.back_results": "返回商品搜索", "market.query_conditions": "实际查询条件", "market.product_specs": "所选商品规格", "market.quote_scope": "成交行情范围", "market.scope_help": "以下价格按接口返回的匹配型号统计，未明确列出的容量、运行内存、颜色等规格未获行情确认。", "market.product_scope_help": "以上为具体商品的规格，不代表成交行情已按所有规格细分。", "market.accept_scope_label": "我接受上述匹配型号范围作为二手参考价。", "market.spec_model": "型号", "market.spec_storage": "存储容量", "market.spec_ram": "运行内存", "market.spec_color": "颜色", "market.spec_version": "版本／渠道", "market.spec_condition": "成色", "market.more_specs": "其他规格", "market.spec_explanation": "规格说明", "market.option_selected": "当前商品", "market.option_unselected": "其他可选值", "market.product_gone": "该商品已不可用，请重新选择，或直接按型号查询。", "market.draft_expired": "查询已过期或服务已重启，请重新搜索。", "market.selection_changed": "商品规格已变化，请重新核对并查询行情。", "market.accept_scope": "请确认接受当前展示的行情范围。"} {
		messages[application.LocaleZhCN][k] = v
	}
	for k, v := range map[string]string{"market.find_products": "Search Zhuanzhuan products", "market.find_help": "Find a matching product, inspect its specifications, then look up the sale reference.", "market.direct": "Query by model directly", "market.use_product": "Use this configuration", "market.asking": "Asking price", "market.view_specs": "View specifications", "market.no_products": "No products found. Adjust the search or query by model directly.", "market.not_provided": "Not provided", "market.back_results": "Back to product search", "market.query_conditions": "Actual query conditions", "market.product_specs": "Selected product specifications", "market.quote_scope": "Sale reference scope", "market.scope_help": "The reference covers the returned model description. Storage, RAM, color and other details not stated there are not confirmed for this quote.", "market.product_scope_help": "These specifications describe this product; the sale reference may cover a broader configuration.", "market.accept_scope_label": "I accept this matched model scope as my secondhand reference.", "market.spec_model": "Model", "market.spec_storage": "Storage", "market.spec_ram": "RAM", "market.spec_color": "Color", "market.spec_version": "Version / channel", "market.spec_condition": "Condition", "market.more_specs": "Other specifications", "market.spec_explanation": "Specification details", "market.option_selected": "This product", "market.option_unselected": "Other option", "market.product_gone": "This product is unavailable. Choose another or query by model directly.", "market.draft_expired": "The query expired or the service restarted. Search again.", "market.selection_changed": "Product specifications changed. Review them and query again.", "market.accept_scope": "Confirm acceptance of the displayed reference scope."} {
		messages[application.LocaleEn][k] = v
	}

	for k, v := range map[string]string{"market.search": "筛选已添加的行情", "market.clear_search": "清除筛选", "market.no_matches": "没有匹配的行情，请更换关键词或清除筛选。", "market.title": "二手行情", "market.reference": "二手参考价", "market.zhuanzhuan": "转转", "market.name": "名称", "market.keyword": "型号关键词", "market.filter": "配置条件（如 256GB）", "market.model": "匹配型号", "market.observed": "获取时间", "market.help": "同款设备可共享行情，每日保存最新成交参考价。", "market.shared": "显式选择同款配置，两台设备可以共用一份行情。", "market.create": "添加二手物品", "market.unbound": "暂不绑定", "market.empty": "暂无二手价格", "market.no_items": "暂无二手物品，添加后可在物品编辑中绑定。", "market.basis": "转转最新一期成交最高价", "market.refresh": "刷新价格", "market.preview": "查询转转行情", "market.confirm": "确认型号并保存", "market.query_again": "重新查询", "market.immutable": "查询配置固定；如需更换型号或配置，请添加新的二手物品。", "market.authentication": "转转凭证无效或已过期，请检查本地配置。", "market.rate_limit": "接口限流，请稍后重试。", "market.temporary": "暂时无法获取行情，原价格已保留。", "market.invalid_response": "接口未返回有效价格，原价格已保留。", "market.unconfigured": "尚未配置转转凭证。请在本地环境配置中设置令牌。", "market.model_changed": "接口匹配型号发生变化，请核对查询配置，原价格已保留。", "market.busy": "正在刷新或已停用，请稍后查看。", "market.fx_pending": "汇率待获取，当前显示原币价格。", "market.failed": "未能完成操作，请检查输入或稍后重试。"} {
		messages[application.LocaleZhCN][k] = v
	}
	for k, v := range map[string]string{"market.search": "Filter saved quotes", "market.clear_search": "Clear filter", "market.no_matches": "No matching quotes. Try another keyword or clear the filter.", "market.title": "Secondhand prices", "market.reference": "Secondhand reference", "market.zhuanzhuan": "Zhuanzhuan", "market.name": "Name", "market.keyword": "Model keywords", "market.filter": "Configuration (e.g. 256GB)", "market.model": "Matched model", "market.observed": "Retrieved at", "market.help": "Share a quote between matching devices. Latest sale references are recorded daily.", "market.shared": "Select the matching configuration. Multiple devices can share one price series.", "market.create": "Add market item", "market.unbound": "No binding", "market.empty": "No secondhand price", "market.no_items": "No market items yet. Add one and bind it in an asset editor.", "market.basis": "Zhuanzhuan latest-period maximum sale price", "market.refresh": "Refresh price", "market.preview": "Look up Zhuanzhuan quote", "market.confirm": "Confirm model and save", "market.query_again": "Query again", "market.immutable": "Query configuration is fixed. Add a new market item for a different model or configuration.", "market.authentication": "Zhuanzhuan credentials are invalid or expired. Check local configuration.", "market.rate_limit": "Rate limited. Retry later.", "market.temporary": "Quote temporarily unavailable. Previous price retained.", "market.invalid_response": "No valid quote returned. Previous price retained.", "market.unconfigured": "Zhuanzhuan is not configured. Set the token in local environment configuration.", "market.model_changed": "Matched model changed. Check the query; previous price retained.", "market.busy": "Refresh is running or the item is disabled. Check again later.", "market.fx_pending": "Exchange rate pending; showing the original quote currency.", "market.failed": "Operation failed. Check the input or retry later."} {
		messages[application.LocaleEn][k] = v
	}
}
