package web

import "github.com/SampsonFox/assetloop/internal/application"

func init() {
	for locale, values := range map[application.Locale]map[string]string{
		application.LocaleZhCN: {
			"validation.specification_retired": "旧规格参数已移除，请使用型号和标签重新提交。",
			"tags.catalog_help":                "型号定义物品身份和可选标签；颜色、容量等描述由具体物品选择。",
			"tags.precedence":                  "物品专属 → 已确认外观默认 → 型号通用。解除绑定后恢复继承，资源文件仍保留。",
			"resource.kind.asset":              "具体物品",
			"appearance.conflict":              "多个同等具体的外观默认指向不同资源，当前已回退型号通用模型或图片。请核对外观默认。",
			"appearance.legacy":                "迁移待处理映射", "appearance.legacy_help": "旧规格缺少外观条件或存在模型冲突。已有物品的原模型已作为专属绑定保留；请配置明确的外观默认后确认处理。确认不会自动解除物品专属绑定，也不会删除历史映射。", "appearance.resolve": "确认已处理", "appearance.resolved": "已处理 · 历史映射保留", "appearance.resolve_confirm": "确认已核对该旧规格映射？这会解除映射对资源删除的保护，但不改动物品专属绑定或删除文件。",
			"appearance.title": "外观默认", "appearance.help": "物品专属优先；外观条件全部匹配时继承最具体的一条，否则使用型号通用模型。", "appearance.confirmed": "已确认绑定", "appearance.none": "尚无外观默认。物品继续使用型号通用模型或图片。", "appearance.edit": "修改外观绑定", "appearance.add": "新增外观绑定", "appearance.no_conditions": "请先在型号中允许外观标签。没有外观条件的模型应绑定为型号通用默认。", "appearance.scope": "检索范围", "appearance.candidates": "同类别、外观标签候选", "appearance.manual": "手工选择全部资源", "appearance.search": "查找模型", "appearance.confirm_help": "先选择条件并查找。候选不代表确认匹配，请预览后确认；同等具体条件指向不同模型时，物品回退通用默认并提示冲突。", "appearance.complete": "外观描述齐全 · 待确认", "appearance.incomplete": "描述不完整 · 请核对", "appearance.unmatched": "未按标签匹配", "appearance.confirm": "确认绑定", "appearance.remove_confirm": "解除此外观默认？物品将重新按剩余规则继承，资源文件不会删除。", "appearance.upload_help": "按上方已查找的外观条件上传并绑定；先选条件并点击查找。GLB 最大 25 MiB，必须自包含。",
			"tags.resource_description": "模型标签与分类", "tags.resource_help": "描述 GLB 实际呈现的特征，用于检索候选；保存不会改变已确认的外观默认或物品专属绑定。", "tags.resource_categories": "可检索类别", "tags.save_resource": "保存模型描述",
			"tags.remove_on_switch": "切换型号将移除以下不再允许的标签，是否继续？", "tags.item_optional": "规格标签均可留空。只展示该型号允许的选项。", "tags.not_selected": "不选择",
			"tags.allowed": "允许标签", "tags.allowed_help": "勾选该型号可选的标签。物品可以留空，不校验厂商规格组合。", "tags.appearance_override": "此型号是否影响外观", "tags.inherit_type": "沿用类型默认", "tags.save_allowed": "保存允许范围", "tags.none_allowed": "未设置可选标签",
			"tags.title": "规格标签管理", "tags.help": "标签描述颜色、容量等特征，类别和产品型号仍独立管理。", "tags.navigation": "标签管理导航", "tags.values": "标签值", "tags.types": "标签类型", "tags.type": "所属类型", "tags.name": "名称", "tags.search": "搜索名称", "tags.all_types": "全部类型", "tags.add_value": "新增标签", "tags.add_type": "新增标签类型", "tags.selection": "选择方式", "tags.single": "单选", "tags.multiple": "允许多选", "tags.appearance": "默认影响外观", "tags.yes": "是", "tags.no": "否", "tags.references": "引用", "tags.no_references": "尚未被引用。", "tags.empty": "没有符合条件的标签。", "tags.value_editor": "编辑标签值", "tags.type_editor": "编辑标签类型", "tags.optional": "所有维度均可留空。型号可以覆盖该维度是否影响外观。", "tags.disable_help": "取消启用后不可新增选择，已有引用和历史展示保留。", "tags.shared": "名称由所有引用者共享。含义改变请新建标签，不要改名替换。", "tags.confirm_rename": "确认仅修正名称，不改变原有含义", "tags.ref.model": "型号允许标签", "tags.ref.appearance": "外观默认", "tags.ref.legacy": "历史规格映射",
			"validation.specification_missing": "标签、类型或型号不存在，请刷新后重试。", "validation.specification_rename_confirmation": "该名称已被引用。请确认只是修正名称，含义改变应新建标签。", "validation.specification_type_immutable": "标签不能改到其他类型，请新建标签。", "validation.specification_disabled": "已停用的标签或类型不可新增选择；已有选择可以保留。", "validation.specification_duplicate": "同一类型下已有该名称，或相同外观条件已有绑定。", "validation.specification_not_allowed": "选择的标签超出了型号允许范围。", "validation.specification_single": "单选类型只能选择一个值。", "validation.specification_appearance": "外观条件必须使用型号允许的外观标签，且不能为空。", "validation.specification_referenced": "已有物品或外观默认引用这些标签，请先处理引用。",
		},
		application.LocaleEn: {
			"validation.specification_retired": "Legacy specification parameters have been removed. Submit a model and tags instead.",
			"tags.catalog_help":                "Models define product identity and allowed tags. Each item selects its own color, storage and other descriptions.",
			"tags.precedence":                  "Item override → confirmed appearance default → model default. Unbinding restores inheritance and keeps the resource file.",
			"resource.kind.asset":              "Item",
			"appearance.conflict":              "Equally specific appearance defaults point to different resources. The model default or image is shown instead. Review the appearance defaults.",
			"appearance.legacy":                "Legacy mappings to review", "appearance.legacy_help": "Legacy specifications lack appearance conditions or have conflicting resources. Existing items retain their original models as overrides. Configure explicit defaults before acknowledging; this neither removes item overrides nor erases the mapping.", "appearance.resolve": "Acknowledge review", "appearance.resolved": "Reviewed · history retained", "appearance.resolve_confirm": "Acknowledge this legacy mapping? It will no longer prevent resource deletion. Item overrides and files are unchanged.",
			"appearance.title": "Appearance defaults", "appearance.help": "Item overrides take priority. All conditions must match; the most specific rule wins, otherwise the model default applies.", "appearance.confirmed": "Confirmed bindings", "appearance.none": "No appearance defaults. Items use the model default or image.", "appearance.edit": "Edit appearance binding", "appearance.add": "Add appearance binding", "appearance.no_conditions": "Allow appearance tags on this model first. Bind resources without appearance conditions as the model default.", "appearance.scope": "Search scope", "appearance.candidates": "Category and appearance candidates", "appearance.manual": "Manually choose any resource", "appearance.search": "Find models", "appearance.confirm_help": "Choose conditions and search, then preview before confirming. Equally specific matches pointing to different resources fall back to the model default with a conflict warning.", "appearance.complete": "Complete description · confirm required", "appearance.incomplete": "Incomplete description · review required", "appearance.unmatched": "Not matched by tags", "appearance.confirm": "Confirm binding", "appearance.remove_confirm": "Remove this appearance default? Items will inherit from remaining rules. The resource file will remain.", "appearance.upload_help": "Upload and bind using the searched conditions above. Select conditions and search first. Self-contained GLB only, up to 25 MiB.",
			"tags.resource_description": "Model tags and categories", "tags.resource_help": "Describe what this GLB depicts to aid discovery. Saving does not change confirmed appearance defaults or item overrides.", "tags.resource_categories": "Searchable categories", "tags.save_resource": "Save model description",
			"tags.remove_on_switch": "Switching models will remove these unavailable tags. Continue?", "tags.item_optional": "All tags are optional. Only this model’s allowed values are shown.", "tags.not_selected": "None",
			"tags.allowed": "Allowed tags", "tags.allowed_help": "Choose the values available for this model. Item selections are optional; manufacturer combinations are not validated.", "tags.appearance_override": "Appearance relevance for this model", "tags.inherit_type": "Use type default", "tags.save_allowed": "Save allowed values", "tags.none_allowed": "No allowed values configured",
			"tags.title": "Specification tags", "tags.help": "Tags describe color, storage and other features. Categories and product models remain separate identities.", "tags.navigation": "Specification navigation", "tags.values": "Tag values", "tags.types": "Tag types", "tags.type": "Type", "tags.name": "Name", "tags.search": "Search names", "tags.all_types": "All types", "tags.add_value": "Add tag", "tags.add_type": "Add tag type", "tags.selection": "Selection", "tags.single": "Single", "tags.multiple": "Allow multiple values", "tags.appearance": "Affects appearance by default", "tags.yes": "Yes", "tags.no": "No", "tags.references": "References", "tags.no_references": "Not referenced yet.", "tags.empty": "No matching tags.", "tags.value_editor": "Edit tag value", "tags.type_editor": "Edit tag type", "tags.optional": "All dimensions are optional. A product model may override appearance relevance.", "tags.disable_help": "Disabling prevents new selections while preserving existing choices and history.", "tags.shared": "All references share this name. Create a new tag when its meaning changes.", "tags.confirm_rename": "This corrects the name without changing its meaning", "tags.ref.model": "Model allowance", "tags.ref.appearance": "Appearance default", "tags.ref.legacy": "Legacy specification mapping",
			"validation.specification_missing": "The tag, type or model was not found. Refresh and try again.", "validation.specification_rename_confirmation": "This name is referenced. Confirm a name correction; create a new tag for a different meaning.", "validation.specification_type_immutable": "A tag cannot move to another type. Create a new tag.", "validation.specification_disabled": "Disabled tags or types cannot be newly selected. Existing choices may be retained.", "validation.specification_duplicate": "The name already exists in this type, or these appearance conditions already have a binding.", "validation.specification_not_allowed": "The selected tags are outside this model’s allowed range.", "validation.specification_single": "Choose at most one value in a single-choice type.", "validation.specification_appearance": "Appearance conditions require at least one allowed appearance tag.", "validation.specification_referenced": "Assets or appearance defaults still reference these tags. Resolve their references first.",
		},
	} {
		for key, value := range values {
			messages[locale][key] = value
		}
	}
}
