// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresdb

import (
	"time"

	"github.com/google/uuid"
)

type Asset struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	VariantID   uuid.UUID
	DisplayName string
	CreatedAt   time.Time
}

type ItemCategory struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	CreatedAt time.Time
}

type ProductModel struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	CategoryID uuid.UUID
	Name       string
	CreatedAt  time.Time
}

type ProductVariant struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	ModelID   uuid.UUID
	Name      string
	CreatedAt time.Time
}

type Tenant struct {
	ID                 uuid.UUID
	Name               string
	BaseCurrency       string
	BaseCurrencyLocked bool
	CreatedAt          time.Time
}
