// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresdb

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Asset struct {
	ID                    uuid.UUID
	TenantID              uuid.UUID
	DisplayName           string
	CreatedAt             time.Time
	SerialNumber          string
	PurchaseChannel       string
	Notes                 string
	Model3dResourceID     uuid.NullUUID
	Model3dResourceStatus string
	ModelID               uuid.UUID
}

type AssetEvent struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	AssetID             uuid.UUID
	TransactionID       uuid.UUID
	EventType           string
	BaseAmountMinor     int64
	BaseCurrency        string
	OriginalAmountMinor sql.NullInt64
	OriginalCurrency    sql.NullString
	FxRateScaled        sql.NullInt64
	FxRateDate          sql.NullTime
	FxRateSource        sql.NullString
	Notes               string
	VoidsEventID        uuid.NullUUID
	ReplacesEventID     uuid.NullUUID
	OccurredAt          time.Time
	CreatedByUserID     uuid.UUID
	CreatedAt           time.Time
	EventTypeID         uuid.UUID
}

type AssetEventType struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	Name              string
	NormalizedName    string
	CashflowDirection string
	CreatedByUserID   uuid.UUID
	CreatedAt         time.Time
	SystemCode        string
	Enabled           bool
	UpdatedAt         time.Time
}

type AssetSpecificationTag struct {
	TenantID uuid.UUID
	AssetID  uuid.UUID
	ModelID  uuid.UUID
	TagID    uuid.UUID
}

type AssetTransaction struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	OccurredAt        time.Time
	Source            string
	ExternalReference string
	Notes             string
	CreatedByUserID   uuid.UUID
	CreatedAt         time.Time
}

type ImportDraft struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	AssetID                uuid.UUID
	EventType              string
	AmountMinor            int64
	Currency               string
	OccurredAt             time.Time
	Source                 string
	ExternalReference      string
	Notes                  string
	RawText                string
	Status                 string
	CreatedByUserID        uuid.UUID
	CreatedAt              time.Time
	ConfirmedTransactionID uuid.NullUUID
}

type ItemCategory struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	CreatedAt time.Time
	IconKey   string
}

type LifecycleRequest struct {
	TenantID    uuid.UUID
	UserID      uuid.UUID
	RequestKey  string
	RequestHash string
	EventID     uuid.UUID
}

type ManagementRequest struct {
	TenantID    uuid.UUID
	UserID      uuid.UUID
	RequestKey  string
	RequestHash string
	ResultJson  string
}

type Model3dResource struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	Status    string
	StoreID   string
	ObjectKey string
	Sha256    string
	SizeBytes int64
	SourceUrl string
	Author    string
	License   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ModelAllowedTag struct {
	TenantID uuid.UUID
	ModelID  uuid.UUID
	TagID    uuid.UUID
}

type ModelAppearanceCondition struct {
	TenantID uuid.UUID
	RuleID   uuid.UUID
	ModelID  uuid.UUID
	TagID    uuid.UUID
}

type ModelAppearanceDefault struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ModelID        uuid.UUID
	ResourceID     uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ResourceStatus string
}

type ModelAppearanceDimension struct {
	TenantID          uuid.UUID
	ModelID           uuid.UUID
	TypeID            uuid.UUID
	AffectsAppearance bool
}

type OauthCredential struct {
	Hash        string
	TenantID    uuid.UUID
	GrantID     uuid.UUID
	Kind        string
	RedirectUri string
	Challenge   string
	ExpiresAt   time.Time
	Consumed    bool
}

type OauthGrant struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	ClientID  string
	Scope     string
	Resource  string
	CreatedAt time.Time
	ExpiresAt time.Time
	Revoked   bool
}

type ProductModel struct {
	ID                    uuid.UUID
	TenantID              uuid.UUID
	CategoryID            uuid.UUID
	Name                  string
	CreatedAt             time.Time
	Model3dStoreID        sql.NullString
	Model3dObjectKey      sql.NullString
	Model3dSha256         sql.NullString
	Model3dSizeBytes      sql.NullInt64
	Model3dSourceUrl      sql.NullString
	Model3dAuthor         sql.NullString
	Model3dLicense        sql.NullString
	Model3dUpdatedAt      sql.NullTime
	Model3dResourceID     uuid.NullUUID
	Model3dResourceStatus string
}

type ResourceCategory struct {
	TenantID   uuid.UUID
	ResourceID uuid.UUID
	CategoryID uuid.UUID
}

type ResourceSpecificationTag struct {
	TenantID   uuid.UUID
	ResourceID uuid.UUID
	TagID      uuid.UUID
}

type SecurityAuditEvent struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	ActorUserID  uuid.NullUUID
	Action       string
	TargetUserID uuid.NullUUID
	Detail       string
	OccurredAt   time.Time
}

type Session struct {
	TokenHash string
	TenantID  uuid.UUID
	UserID    uuid.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
}

type SpecificationTag struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	TypeID         uuid.UUID
	Name           string
	NormalizedName string
	Enabled        bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type SpecificationTagType struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	Name              string
	NormalizedName    string
	Multiple          bool
	AffectsAppearance bool
	Enabled           bool
	SystemCode        string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Tenant struct {
	ID                 uuid.UUID
	Name               string
	BaseCurrency       string
	BaseCurrencyLocked bool
	CreatedAt          time.Time
}

type TenantMembership struct {
	TenantID  uuid.UUID
	UserID    uuid.UUID
	Role      string
	CreatedAt time.Time
}

type User struct {
	ID                 uuid.UUID
	Username           string
	UsernameNormalized string
	PasswordHash       string
	CreatedAt          time.Time
	Locale             string
	Theme              string
	Accent             string
}
