// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package postgresdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeOAuthCredential = `-- name: ConsumeOAuthCredential :execrows
UPDATE oauth_credentials SET consumed = TRUE WHERE hash = $1 AND consumed = FALSE
`

func (q *Queries) ConsumeOAuthCredential(ctx context.Context, hash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeOAuthCredential, hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOAuthCredential = `-- name: GetOAuthCredential :one
SELECT hash, tenant_id, grant_id, kind, redirect_uri, challenge, expires_at, consumed FROM oauth_credentials WHERE hash = $1
`

func (q *Queries) GetOAuthCredential(ctx context.Context, hash string) (OauthCredential, error) {
	row := q.db.QueryRowContext(ctx, getOAuthCredential, hash)
	var i OauthCredential
	err := row.Scan(
		&i.Hash,
		&i.TenantID,
		&i.GrantID,
		&i.Kind,
		&i.RedirectUri,
		&i.Challenge,
		&i.ExpiresAt,
		&i.Consumed,
	)
	return i, err
}

const getOAuthGrant = `-- name: GetOAuthGrant :one
SELECT id, tenant_id, user_id, client_id, scope, resource, created_at, expires_at, revoked FROM oauth_grants WHERE id = $1
`

func (q *Queries) GetOAuthGrant(ctx context.Context, id uuid.UUID) (OauthGrant, error) {
	row := q.db.QueryRowContext(ctx, getOAuthGrant, id)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ClientID,
		&i.Scope,
		&i.Resource,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const listOAuthGrants = `-- name: ListOAuthGrants :many
SELECT id, tenant_id, user_id, client_id, scope, resource, created_at, expires_at, revoked FROM oauth_grants WHERE tenant_id = $1 AND user_id = $2
ORDER BY created_at DESC, id
`

type ListOAuthGrantsParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) ListOAuthGrants(ctx context.Context, arg ListOAuthGrantsParams) ([]OauthGrant, error) {
	rows, err := q.db.QueryContext(ctx, listOAuthGrants, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthGrant
	for rows.Next() {
		var i OauthGrant
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ClientID,
			&i.Scope,
			&i.Resource,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOAuthWrites = `-- name: LockOAuthWrites :exec
SELECT pg_advisory_xact_lock(716044113)
`

func (q *Queries) LockOAuthWrites(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, lockOAuthWrites)
	return err
}

const oAuthPrincipal = `-- name: OAuthPrincipal :one
SELECT tm.tenant_id, tm.user_id, u.username, tm.role, t.name AS tenant_name,
       u.locale, u.theme, u.accent
FROM tenant_memberships tm
JOIN users u ON u.id = tm.user_id
JOIN tenants t ON t.id = tm.tenant_id
WHERE tm.tenant_id = $1 AND tm.user_id = $2
`

type OAuthPrincipalParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

type OAuthPrincipalRow struct {
	TenantID   uuid.UUID
	UserID     uuid.UUID
	Username   string
	Role       string
	TenantName string
	Locale     string
	Theme      string
	Accent     string
}

func (q *Queries) OAuthPrincipal(ctx context.Context, arg OAuthPrincipalParams) (OAuthPrincipalRow, error) {
	row := q.db.QueryRowContext(ctx, oAuthPrincipal, arg.TenantID, arg.UserID)
	var i OAuthPrincipalRow
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.TenantName,
		&i.Locale,
		&i.Theme,
		&i.Accent,
	)
	return i, err
}

const putOAuthCredential = `-- name: PutOAuthCredential :exec
INSERT INTO oauth_credentials (hash, tenant_id, grant_id, kind, redirect_uri, challenge, expires_at, consumed)
VALUES ($1, $2, $3, $4,
$5, $6, $7, $8)
`

type PutOAuthCredentialParams struct {
	Hash        string
	TenantID    uuid.UUID
	GrantID     uuid.UUID
	Kind        string
	RedirectUri string
	Challenge   string
	ExpiresAt   time.Time
	Consumed    bool
}

func (q *Queries) PutOAuthCredential(ctx context.Context, arg PutOAuthCredentialParams) error {
	_, err := q.db.ExecContext(ctx, putOAuthCredential,
		arg.Hash,
		arg.TenantID,
		arg.GrantID,
		arg.Kind,
		arg.RedirectUri,
		arg.Challenge,
		arg.ExpiresAt,
		arg.Consumed,
	)
	return err
}

const putOAuthGrant = `-- name: PutOAuthGrant :exec
INSERT INTO oauth_grants (id, tenant_id, user_id, client_id, scope, resource, created_at, expires_at, revoked)
VALUES ($1, $2, $3, $4,
$5, $6, $7, $8, $9)
`

type PutOAuthGrantParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	ClientID  string
	Scope     string
	Resource  string
	CreatedAt time.Time
	ExpiresAt time.Time
	Revoked   bool
}

func (q *Queries) PutOAuthGrant(ctx context.Context, arg PutOAuthGrantParams) error {
	_, err := q.db.ExecContext(ctx, putOAuthGrant,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.ClientID,
		arg.Scope,
		arg.Resource,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.Revoked,
	)
	return err
}

const revokeOAuthGrant = `-- name: RevokeOAuthGrant :exec
UPDATE oauth_grants SET revoked = TRUE WHERE id = $1
`

func (q *Queries) RevokeOAuthGrant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeOAuthGrant, id)
	return err
}
