// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package postgresdb

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countAssetsWithSummary = `-- name: CountAssetsWithSummary :one
WITH effective_events AS (
SELECT e.id, e.tenant_id, e.asset_id, e.transaction_id, e.event_type, e.base_amount_minor, e.base_currency, e.original_amount_minor, e.original_currency, e.fx_rate_scaled, e.fx_rate_date, e.fx_rate_source, e.notes, e.voids_event_id, e.replaces_event_id, e.occurred_at, e.created_by_user_id, e.created_at
FROM asset_events e
WHERE e.tenant_id = $2
  AND e.event_type != 'void'
  AND NOT EXISTS (
      SELECT 1 FROM asset_events void_event
      WHERE void_event.tenant_id = e.tenant_id AND void_event.voids_event_id = e.id
  )
),
event_rollup AS (
SELECT asset_id,
       BOOL_OR(event_type = 'purchase') AS has_purchase,
       BOOL_OR(event_type = 'sale') AS has_sale
FROM effective_events
GROUP BY asset_id
),
ranked_events AS (
SELECT asset_id, event_type,
       ROW_NUMBER() OVER (PARTITION BY asset_id ORDER BY occurred_at DESC, created_at DESC, id DESC) AS event_rank
FROM effective_events
WHERE event_type IN ('purchase', 'repair', 'sale')
),
asset_rows AS (
SELECT a.id,
       COALESCE(er.has_purchase, FALSE) AS has_purchase,
       COALESCE(er.has_sale, FALSE) AS has_sale,
       COALESCE(re.event_type, '') AS latest_event_type
FROM assets a
JOIN product_variants v ON v.tenant_id = a.tenant_id AND v.id = a.variant_id
JOIN product_models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
LEFT JOIN event_rollup er ON er.asset_id = a.id
LEFT JOIN ranked_events re ON re.asset_id = a.id AND re.event_rank = 1
WHERE a.tenant_id = $2
  AND ($3::text = '' OR (
       a.display_name ILIKE '%' || $3::text || '%' OR
       a.serial_number ILIKE '%' || $3::text || '%' OR
       a.color ILIKE '%' || $3::text || '%' OR
       a.purchase_channel ILIKE '%' || $3::text || '%' OR
       a.notes ILIKE '%' || $3::text || '%' OR
       m.name ILIKE '%' || $3::text || '%' OR
       v.name ILIKE '%' || $3::text || '%' OR
       c.name ILIKE '%' || $3::text || '%'
  ))
)
SELECT COUNT(*) FROM asset_rows
WHERE $1::text IN ('', 'all')
   OR ($1::text = 'sold' AND has_sale)
   OR ($1::text = 'repairing' AND NOT has_sale AND has_purchase AND latest_event_type = 'repair')
   OR ($1::text = 'active' AND NOT has_sale AND has_purchase AND latest_event_type != 'repair')
   OR ($1::text = 'unacquired' AND NOT has_sale AND NOT has_purchase)
`

type CountAssetsWithSummaryParams struct {
	StatusFilter string
	TenantID     uuid.UUID
	SearchQuery  string
}

func (q *Queries) CountAssetsWithSummary(ctx context.Context, arg CountAssetsWithSummaryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAssetsWithSummary, arg.StatusFilter, arg.TenantID, arg.SearchQuery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :exec
INSERT INTO assets (id, tenant_id, variant_id, display_name, created_at) VALUES ($1, $2, $3, $4, $5)
`

type CreateAssetParams struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	VariantID   uuid.UUID
	DisplayName string
	CreatedAt   time.Time
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) error {
	_, err := q.db.ExecContext(ctx, createAsset,
		arg.ID,
		arg.TenantID,
		arg.VariantID,
		arg.DisplayName,
		arg.CreatedAt,
	)
	return err
}

const createAssetEvent = `-- name: CreateAssetEvent :exec
INSERT INTO asset_events
    (id, tenant_id, asset_id, transaction_id, event_type, base_amount_minor,
     base_currency, original_amount_minor, original_currency, fx_rate_scaled,
     fx_rate_date, fx_rate_source, notes, voids_event_id, replaces_event_id,
     occurred_at, created_by_user_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
`

type CreateAssetEventParams struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	AssetID             uuid.UUID
	TransactionID       uuid.UUID
	EventType           string
	BaseAmountMinor     int64
	BaseCurrency        string
	OriginalAmountMinor sql.NullInt64
	OriginalCurrency    sql.NullString
	FxRateScaled        sql.NullInt64
	FxRateDate          sql.NullTime
	FxRateSource        sql.NullString
	Notes               string
	VoidsEventID        uuid.NullUUID
	ReplacesEventID     uuid.NullUUID
	OccurredAt          time.Time
	CreatedByUserID     uuid.UUID
	CreatedAt           time.Time
}

func (q *Queries) CreateAssetEvent(ctx context.Context, arg CreateAssetEventParams) error {
	_, err := q.db.ExecContext(ctx, createAssetEvent,
		arg.ID,
		arg.TenantID,
		arg.AssetID,
		arg.TransactionID,
		arg.EventType,
		arg.BaseAmountMinor,
		arg.BaseCurrency,
		arg.OriginalAmountMinor,
		arg.OriginalCurrency,
		arg.FxRateScaled,
		arg.FxRateDate,
		arg.FxRateSource,
		arg.Notes,
		arg.VoidsEventID,
		arg.ReplacesEventID,
		arg.OccurredAt,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	return err
}

const createAssetEventType = `-- name: CreateAssetEventType :exec
INSERT INTO asset_event_types
    (id, tenant_id, name, normalized_name, cashflow_direction, created_by_user_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAssetEventTypeParams struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	Name              string
	NormalizedName    string
	CashflowDirection string
	CreatedByUserID   uuid.UUID
	CreatedAt         time.Time
}

func (q *Queries) CreateAssetEventType(ctx context.Context, arg CreateAssetEventTypeParams) error {
	_, err := q.db.ExecContext(ctx, createAssetEventType,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.NormalizedName,
		arg.CashflowDirection,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	return err
}

const createAssetTransaction = `-- name: CreateAssetTransaction :exec
INSERT INTO asset_transactions
    (id, tenant_id, occurred_at, source, external_reference, notes, created_by_user_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAssetTransactionParams struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	OccurredAt        time.Time
	Source            string
	ExternalReference string
	Notes             string
	CreatedByUserID   uuid.UUID
	CreatedAt         time.Time
}

func (q *Queries) CreateAssetTransaction(ctx context.Context, arg CreateAssetTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createAssetTransaction,
		arg.ID,
		arg.TenantID,
		arg.OccurredAt,
		arg.Source,
		arg.ExternalReference,
		arg.Notes,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	return err
}

const createCatalogAsset = `-- name: CreateCatalogAsset :exec
INSERT INTO assets
    (id, tenant_id, variant_id, display_name, serial_number, color, purchase_channel, notes, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateCatalogAssetParams struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	VariantID       uuid.UUID
	DisplayName     string
	SerialNumber    string
	Color           string
	PurchaseChannel string
	Notes           string
	CreatedAt       time.Time
}

func (q *Queries) CreateCatalogAsset(ctx context.Context, arg CreateCatalogAssetParams) error {
	_, err := q.db.ExecContext(ctx, createCatalogAsset,
		arg.ID,
		arg.TenantID,
		arg.VariantID,
		arg.DisplayName,
		arg.SerialNumber,
		arg.Color,
		arg.PurchaseChannel,
		arg.Notes,
		arg.CreatedAt,
	)
	return err
}

const createCategory = `-- name: CreateCategory :exec
INSERT INTO item_categories (id, tenant_id, name, icon_key, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateCategoryParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	IconKey   string
	CreatedAt time.Time
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.IconKey,
		arg.CreatedAt,
	)
	return err
}

const createMembership = `-- name: CreateMembership :exec
INSERT INTO tenant_memberships (tenant_id, user_id, role, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateMembershipParams struct {
	TenantID  uuid.UUID
	UserID    uuid.UUID
	Role      string
	CreatedAt time.Time
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.ExecContext(ctx, createMembership,
		arg.TenantID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const createModel = `-- name: CreateModel :exec
INSERT INTO product_models (id, tenant_id, category_id, name, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateModelParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	CategoryID uuid.UUID
	Name       string
	CreatedAt  time.Time
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) error {
	_, err := q.db.ExecContext(ctx, createModel,
		arg.ID,
		arg.TenantID,
		arg.CategoryID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const createSecurityAuditEvent = `-- name: CreateSecurityAuditEvent :exec
INSERT INTO security_audit_events
    (id, tenant_id, actor_user_id, action, target_user_id, detail, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSecurityAuditEventParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	ActorUserID  uuid.NullUUID
	Action       string
	TargetUserID uuid.NullUUID
	Detail       string
	OccurredAt   time.Time
}

func (q *Queries) CreateSecurityAuditEvent(ctx context.Context, arg CreateSecurityAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, createSecurityAuditEvent,
		arg.ID,
		arg.TenantID,
		arg.ActorUserID,
		arg.Action,
		arg.TargetUserID,
		arg.Detail,
		arg.OccurredAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, tenant_id, user_id, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	TokenHash string
	TenantID  uuid.UUID
	UserID    uuid.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.TenantID,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createTenant = `-- name: CreateTenant :exec
INSERT INTO tenants (id, name, base_currency, created_at) VALUES ($1, $2, $3, $4)
`

type CreateTenantParams struct {
	ID           uuid.UUID
	Name         string
	BaseCurrency string
	CreatedAt    time.Time
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.ExecContext(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.BaseCurrency,
		arg.CreatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, username_normalized, password_hash, locale, theme, accent, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateUserParams struct {
	ID                 uuid.UUID
	Username           string
	UsernameNormalized string
	PasswordHash       string
	Locale             string
	Theme              string
	Accent             string
	CreatedAt          time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.UsernameNormalized,
		arg.PasswordHash,
		arg.Locale,
		arg.Theme,
		arg.Accent,
		arg.CreatedAt,
	)
	return err
}

const createVariant = `-- name: CreateVariant :exec
INSERT INTO product_variants (id, tenant_id, model_id, name, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateVariantParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	ModelID   uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) error {
	_, err := q.db.ExecContext(ctx, createVariant,
		arg.ID,
		arg.TenantID,
		arg.ModelID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const deleteVariant = `-- name: DeleteVariant :execrows
DELETE FROM product_variants AS variant
WHERE variant.tenant_id = $1 AND variant.id = $2
  AND NOT EXISTS (
    SELECT 1 FROM assets
    WHERE assets.tenant_id = variant.tenant_id
      AND assets.variant_id = variant.id
  )
`

type DeleteVariantParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) DeleteVariant(ctx context.Context, arg DeleteVariantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVariant, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensureCategory = `-- name: EnsureCategory :one
INSERT INTO item_categories (id, tenant_id, name, created_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, name) DO UPDATE SET name = excluded.name
RETURNING id
`

type EnsureCategoryParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) EnsureCategory(ctx context.Context, arg EnsureCategoryParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, ensureCategory,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const ensureModel = `-- name: EnsureModel :one
INSERT INTO product_models (id, tenant_id, category_id, name, created_at) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, category_id, name) DO UPDATE SET name = excluded.name
RETURNING id
`

type EnsureModelParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	CategoryID uuid.UUID
	Name       string
	CreatedAt  time.Time
}

func (q *Queries) EnsureModel(ctx context.Context, arg EnsureModelParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, ensureModel,
		arg.ID,
		arg.TenantID,
		arg.CategoryID,
		arg.Name,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const ensureTenant = `-- name: EnsureTenant :exec
INSERT INTO tenants (id, name, base_currency, created_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO NOTHING
`

type EnsureTenantParams struct {
	ID           uuid.UUID
	Name         string
	BaseCurrency string
	CreatedAt    time.Time
}

func (q *Queries) EnsureTenant(ctx context.Context, arg EnsureTenantParams) error {
	_, err := q.db.ExecContext(ctx, ensureTenant,
		arg.ID,
		arg.Name,
		arg.BaseCurrency,
		arg.CreatedAt,
	)
	return err
}

const ensureVariant = `-- name: EnsureVariant :one
INSERT INTO product_variants (id, tenant_id, model_id, name, created_at) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, model_id, name) DO UPDATE SET name = excluded.name
RETURNING id
`

type EnsureVariantParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	ModelID   uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) EnsureVariant(ctx context.Context, arg EnsureVariantParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, ensureVariant,
		arg.ID,
		arg.TenantID,
		arg.ModelID,
		arg.Name,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findAccountByUsername = `-- name: FindAccountByUsername :one
SELECT u.id AS user_id, u.username, u.password_hash, u.locale, u.theme, u.accent,
       tm.tenant_id, tm.role, t.name AS tenant_name
FROM users u
JOIN tenant_memberships tm ON tm.user_id = u.id
JOIN tenants t ON t.id = tm.tenant_id
WHERE u.username_normalized = $1
ORDER BY tm.created_at
LIMIT 1
`

type FindAccountByUsernameRow struct {
	UserID       uuid.UUID
	Username     string
	PasswordHash string
	Locale       string
	Theme        string
	Accent       string
	TenantID     uuid.UUID
	Role         string
	TenantName   string
}

func (q *Queries) FindAccountByUsername(ctx context.Context, usernameNormalized string) (FindAccountByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, findAccountByUsername, usernameNormalized)
	var i FindAccountByUsernameRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.PasswordHash,
		&i.Locale,
		&i.Theme,
		&i.Accent,
		&i.TenantID,
		&i.Role,
		&i.TenantName,
	)
	return i, err
}

const findLifecycleRequest = `-- name: FindLifecycleRequest :one
SELECT request_hash, event_id FROM lifecycle_requests
WHERE tenant_id = $1 AND user_id = $2 AND request_key = $3
`

type FindLifecycleRequestParams struct {
	TenantID   uuid.UUID
	UserID     uuid.UUID
	RequestKey string
}

type FindLifecycleRequestRow struct {
	RequestHash string
	EventID     uuid.UUID
}

func (q *Queries) FindLifecycleRequest(ctx context.Context, arg FindLifecycleRequestParams) (FindLifecycleRequestRow, error) {
	row := q.db.QueryRowContext(ctx, findLifecycleRequest, arg.TenantID, arg.UserID, arg.RequestKey)
	var i FindLifecycleRequestRow
	err := row.Scan(&i.RequestHash, &i.EventID)
	return i, err
}

const firstPrincipal = `-- name: FirstPrincipal :one
SELECT tm.tenant_id, u.id AS user_id, u.username, tm.role, t.name AS tenant_name,
       u.locale, u.theme, u.accent
FROM users u
JOIN tenant_memberships tm ON tm.user_id = u.id
JOIN tenants t ON t.id = tm.tenant_id
ORDER BY u.created_at, tm.created_at
LIMIT 1
`

type FirstPrincipalRow struct {
	TenantID   uuid.UUID
	UserID     uuid.UUID
	Username   string
	Role       string
	TenantName string
	Locale     string
	Theme      string
	Accent     string
}

func (q *Queries) FirstPrincipal(ctx context.Context) (FirstPrincipalRow, error) {
	row := q.db.QueryRowContext(ctx, firstPrincipal)
	var i FirstPrincipalRow
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.TenantName,
		&i.Locale,
		&i.Theme,
		&i.Accent,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT a.id, a.tenant_id, c.id AS category_id, c.name AS category_name,
       c.icon_key AS category_icon,
       m.id AS model_id, m.name AS model_name, v.id AS variant_id,
       v.name AS variant_name, a.display_name, a.serial_number, a.color,
       a.purchase_channel, a.notes, a.created_at
FROM assets a
JOIN product_variants v ON v.tenant_id = a.tenant_id AND v.id = a.variant_id
JOIN product_models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
WHERE a.tenant_id = $1 AND a.id = $2
`

type GetAssetParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetAssetRow struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	CategoryID      uuid.UUID
	CategoryName    string
	CategoryIcon    string
	ModelID         uuid.UUID
	ModelName       string
	VariantID       uuid.UUID
	VariantName     string
	DisplayName     string
	SerialNumber    string
	Color           string
	PurchaseChannel string
	Notes           string
	CreatedAt       time.Time
}

func (q *Queries) GetAsset(ctx context.Context, arg GetAssetParams) (GetAssetRow, error) {
	row := q.db.QueryRowContext(ctx, getAsset, arg.TenantID, arg.ID)
	var i GetAssetRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategoryIcon,
		&i.ModelID,
		&i.ModelName,
		&i.VariantID,
		&i.VariantName,
		&i.DisplayName,
		&i.SerialNumber,
		&i.Color,
		&i.PurchaseChannel,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetEvent = `-- name: GetAssetEvent :one
SELECT e.id, e.tenant_id, e.asset_id, e.transaction_id, e.event_type,
       e.base_amount_minor, e.base_currency, e.original_amount_minor,
       e.original_currency, e.fx_rate_scaled, e.fx_rate_date, e.fx_rate_source,
       e.notes, e.voids_event_id, e.replaces_event_id, e.occurred_at,
       e.created_by_user_id, e.created_at,
       EXISTS (
           SELECT 1 FROM asset_events v
           WHERE v.tenant_id = e.tenant_id AND v.voids_event_id = e.id
       ) AS is_voided
FROM asset_events e
WHERE e.tenant_id = $1 AND e.id = $2
`

type GetAssetEventParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetAssetEventRow struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	AssetID             uuid.UUID
	TransactionID       uuid.UUID
	EventType           string
	BaseAmountMinor     int64
	BaseCurrency        string
	OriginalAmountMinor sql.NullInt64
	OriginalCurrency    sql.NullString
	FxRateScaled        sql.NullInt64
	FxRateDate          sql.NullTime
	FxRateSource        sql.NullString
	Notes               string
	VoidsEventID        uuid.NullUUID
	ReplacesEventID     uuid.NullUUID
	OccurredAt          time.Time
	CreatedByUserID     uuid.UUID
	CreatedAt           time.Time
	IsVoided            bool
}

func (q *Queries) GetAssetEvent(ctx context.Context, arg GetAssetEventParams) (GetAssetEventRow, error) {
	row := q.db.QueryRowContext(ctx, getAssetEvent, arg.TenantID, arg.ID)
	var i GetAssetEventRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetID,
		&i.TransactionID,
		&i.EventType,
		&i.BaseAmountMinor,
		&i.BaseCurrency,
		&i.OriginalAmountMinor,
		&i.OriginalCurrency,
		&i.FxRateScaled,
		&i.FxRateDate,
		&i.FxRateSource,
		&i.Notes,
		&i.VoidsEventID,
		&i.ReplacesEventID,
		&i.OccurredAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.IsVoided,
	)
	return i, err
}

const getAssetSummary = `-- name: GetAssetSummary :one
WITH effective_events AS (
    SELECT e.id, e.tenant_id, e.asset_id, e.transaction_id, e.event_type, e.base_amount_minor, e.base_currency, e.original_amount_minor, e.original_currency, e.fx_rate_scaled, e.fx_rate_date, e.fx_rate_source, e.notes, e.voids_event_id, e.replaces_event_id, e.occurred_at, e.created_by_user_id, e.created_at
    FROM asset_events e
    WHERE e.tenant_id = $2 AND e.asset_id = $1
      AND e.event_type != 'void'
      AND NOT EXISTS (SELECT 1 FROM asset_events v WHERE v.tenant_id = e.tenant_id AND v.voids_event_id = e.id)
), latest_event AS (
    SELECT event_type FROM effective_events
    WHERE event_type IN ('purchase', 'repair', 'sale')
    ORDER BY occurred_at DESC, created_at DESC, id DESC LIMIT 1
)
SELECT t.base_currency::text AS base_currency,
       COALESCE(SUM(CASE WHEN e.base_amount_minor < 0 THEN -e.base_amount_minor ELSE 0 END), 0)::bigint AS expense_minor,
       COALESCE(SUM(CASE WHEN e.base_amount_minor > 0 THEN e.base_amount_minor ELSE 0 END), 0)::bigint AS income_minor,
       COALESCE(SUM(e.base_amount_minor), 0)::bigint AS net_minor,
       CASE
         WHEN COALESCE(BOOL_OR(e.event_type = 'sale'), FALSE) THEN 'sold'
         WHEN NOT COALESCE(BOOL_OR(e.event_type = 'purchase'), FALSE) THEN 'unacquired'
         WHEN COALESCE((SELECT event_type FROM latest_event), '') = 'repair' THEN 'repairing'
         ELSE 'active'
       END::text AS status
FROM tenants t
JOIN assets a ON a.tenant_id = t.id AND a.id = $1
LEFT JOIN effective_events e ON e.asset_id = a.id
WHERE t.id = $2
GROUP BY t.base_currency
`

type GetAssetSummaryParams struct {
	AssetID  uuid.UUID
	TenantID uuid.UUID
}

type GetAssetSummaryRow struct {
	BaseCurrency string
	ExpenseMinor int64
	IncomeMinor  int64
	NetMinor     int64
	Status       string
}

func (q *Queries) GetAssetSummary(ctx context.Context, arg GetAssetSummaryParams) (GetAssetSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getAssetSummary, arg.AssetID, arg.TenantID)
	var i GetAssetSummaryRow
	err := row.Scan(
		&i.BaseCurrency,
		&i.ExpenseMinor,
		&i.IncomeMinor,
		&i.NetMinor,
		&i.Status,
	)
	return i, err
}

const getPortfolioSummary = `-- name: GetPortfolioSummary :one
WITH effective_events AS (
    SELECT e.id, e.tenant_id, e.asset_id, e.transaction_id, e.event_type, e.base_amount_minor, e.base_currency, e.original_amount_minor, e.original_currency, e.fx_rate_scaled, e.fx_rate_date, e.fx_rate_source, e.notes, e.voids_event_id, e.replaces_event_id, e.occurred_at, e.created_by_user_id, e.created_at
    FROM asset_events e
    WHERE e.tenant_id = $1
      AND e.event_type != 'void'
      AND NOT EXISTS (
          SELECT 1 FROM asset_events void_event
          WHERE void_event.tenant_id = e.tenant_id AND void_event.voids_event_id = e.id
      )
)
SELECT COUNT(DISTINCT a.id)::bigint AS asset_count,
       COALESCE(SUM(CASE WHEN e.base_amount_minor < 0 THEN -e.base_amount_minor ELSE 0 END), 0)::bigint AS expense_minor,
       COALESCE(SUM(CASE WHEN e.base_amount_minor > 0 THEN e.base_amount_minor ELSE 0 END), 0)::bigint AS income_minor,
       COALESCE(SUM(e.base_amount_minor), 0)::bigint AS net_minor,
       t.base_currency::text AS base_currency
FROM tenants t
LEFT JOIN assets a ON a.tenant_id = t.id
LEFT JOIN effective_events e ON e.asset_id = a.id
WHERE t.id = $1
GROUP BY t.base_currency
`

type GetPortfolioSummaryRow struct {
	AssetCount   int64
	ExpenseMinor int64
	IncomeMinor  int64
	NetMinor     int64
	BaseCurrency string
}

func (q *Queries) GetPortfolioSummary(ctx context.Context, tenantID uuid.UUID) (GetPortfolioSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getPortfolioSummary, tenantID)
	var i GetPortfolioSummaryRow
	err := row.Scan(
		&i.AssetCount,
		&i.ExpenseMinor,
		&i.IncomeMinor,
		&i.NetMinor,
		&i.BaseCurrency,
	)
	return i, err
}

const getSessionPrincipal = `-- name: GetSessionPrincipal :one
SELECT s.tenant_id, s.user_id, u.username, tm.role, t.name AS tenant_name,
       u.locale, u.theme, u.accent
FROM sessions s
JOIN users u ON u.id = s.user_id
JOIN tenant_memberships tm ON tm.tenant_id = s.tenant_id AND tm.user_id = s.user_id
JOIN tenants t ON t.id = s.tenant_id
WHERE s.token_hash = $1 AND s.expires_at > $2
`

type GetSessionPrincipalParams struct {
	TokenHash string
	ExpiresAt time.Time
}

type GetSessionPrincipalRow struct {
	TenantID   uuid.UUID
	UserID     uuid.UUID
	Username   string
	Role       string
	TenantName string
	Locale     string
	Theme      string
	Accent     string
}

func (q *Queries) GetSessionPrincipal(ctx context.Context, arg GetSessionPrincipalParams) (GetSessionPrincipalRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionPrincipal, arg.TokenHash, arg.ExpiresAt)
	var i GetSessionPrincipalRow
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.TenantName,
		&i.Locale,
		&i.Theme,
		&i.Accent,
	)
	return i, err
}

const getTenantBaseCurrency = `-- name: GetTenantBaseCurrency :one
SELECT base_currency, base_currency_locked
FROM tenants
WHERE id = $1
`

type GetTenantBaseCurrencyRow struct {
	BaseCurrency       string
	BaseCurrencyLocked bool
}

func (q *Queries) GetTenantBaseCurrency(ctx context.Context, id uuid.UUID) (GetTenantBaseCurrencyRow, error) {
	row := q.db.QueryRowContext(ctx, getTenantBaseCurrency, id)
	var i GetTenantBaseCurrencyRow
	err := row.Scan(&i.BaseCurrency, &i.BaseCurrencyLocked)
	return i, err
}

const listAssetEventTypes = `-- name: ListAssetEventTypes :many
SELECT id, tenant_id, name, normalized_name, cashflow_direction, created_by_user_id, created_at
FROM asset_event_types
WHERE tenant_id = $1
ORDER BY normalized_name, id
`

func (q *Queries) ListAssetEventTypes(ctx context.Context, tenantID uuid.UUID) ([]AssetEventType, error) {
	rows, err := q.db.QueryContext(ctx, listAssetEventTypes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetEventType
	for rows.Next() {
		var i AssetEventType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.NormalizedName,
			&i.CashflowDirection,
			&i.CreatedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetEvents = `-- name: ListAssetEvents :many
SELECT e.id, e.tenant_id, e.asset_id, e.transaction_id, e.event_type,
       e.base_amount_minor, e.base_currency, e.original_amount_minor,
       e.original_currency, e.fx_rate_scaled, e.fx_rate_date, e.fx_rate_source,
       e.notes, e.voids_event_id, e.replaces_event_id, e.occurred_at,
       e.created_by_user_id, e.created_at,
       EXISTS (
           SELECT 1 FROM asset_events v
           WHERE v.tenant_id = e.tenant_id AND v.voids_event_id = e.id
       ) AS is_voided
FROM asset_events e
WHERE e.tenant_id = $1 AND e.asset_id = $2
ORDER BY e.occurred_at, e.created_at, e.id
`

type ListAssetEventsParams struct {
	TenantID uuid.UUID
	AssetID  uuid.UUID
}

type ListAssetEventsRow struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	AssetID             uuid.UUID
	TransactionID       uuid.UUID
	EventType           string
	BaseAmountMinor     int64
	BaseCurrency        string
	OriginalAmountMinor sql.NullInt64
	OriginalCurrency    sql.NullString
	FxRateScaled        sql.NullInt64
	FxRateDate          sql.NullTime
	FxRateSource        sql.NullString
	Notes               string
	VoidsEventID        uuid.NullUUID
	ReplacesEventID     uuid.NullUUID
	OccurredAt          time.Time
	CreatedByUserID     uuid.UUID
	CreatedAt           time.Time
	IsVoided            bool
}

func (q *Queries) ListAssetEvents(ctx context.Context, arg ListAssetEventsParams) ([]ListAssetEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetEvents, arg.TenantID, arg.AssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetEventsRow
	for rows.Next() {
		var i ListAssetEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssetID,
			&i.TransactionID,
			&i.EventType,
			&i.BaseAmountMinor,
			&i.BaseCurrency,
			&i.OriginalAmountMinor,
			&i.OriginalCurrency,
			&i.FxRateScaled,
			&i.FxRateDate,
			&i.FxRateSource,
			&i.Notes,
			&i.VoidsEventID,
			&i.ReplacesEventID,
			&i.OccurredAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.IsVoided,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetEventsPage = `-- name: ListAssetEventsPage :many
WITH RECURSIVE event_lineage (id, root_created_at) AS (
    SELECT id, created_at
    FROM asset_events
    WHERE tenant_id = $1 AND asset_id = $2 AND replaces_event_id IS NULL
    UNION ALL
    SELECT e.id, lineage.root_created_at
    FROM asset_events e
    JOIN event_lineage lineage ON lineage.id = e.replaces_event_id
    WHERE e.tenant_id = $1 AND e.asset_id = $2
)
SELECT e.id, e.tenant_id, e.asset_id, e.transaction_id, e.event_type,
       e.base_amount_minor, e.base_currency, e.original_amount_minor,
       e.original_currency, e.fx_rate_scaled, e.fx_rate_date, e.fx_rate_source,
       e.notes, e.voids_event_id, e.replaces_event_id, e.occurred_at,
       e.created_by_user_id, e.created_at,
       EXISTS (
           SELECT 1 FROM asset_events v
           WHERE v.tenant_id = e.tenant_id AND v.voids_event_id = e.id
       ) AS is_voided,
       COUNT(*) OVER ()::bigint AS total_count
FROM asset_events e
JOIN event_lineage lineage ON lineage.id = e.id
WHERE e.tenant_id = $1 AND e.asset_id = $2
  AND e.event_type != 'void'
  AND ($3::boolean OR NOT EXISTS (
      SELECT 1 FROM asset_events v
      WHERE v.tenant_id = e.tenant_id AND v.voids_event_id = e.id
  ))
  AND ($4::text = '' OR e.notes ILIKE '%' || $4::text || '%' OR COALESCE(e.fx_rate_source, '') ILIKE '%' || $4::text || '%')
  AND ($5::text = '' OR e.event_type = $5::text)
ORDER BY
  CASE WHEN $6::text = 'occurred' AND $7::text = 'asc' THEN e.occurred_at END ASC,
  CASE WHEN $6::text = 'occurred' AND $7::text = 'desc' THEN e.occurred_at END DESC,
  CASE WHEN $6::text = 'occurred' AND $7::text = 'asc' THEN lineage.root_created_at END ASC,
  CASE WHEN $6::text = 'occurred' AND $7::text = 'desc' THEN lineage.root_created_at END DESC,
  CASE WHEN $6::text = 'occurred' AND $7::text = 'asc' THEN e.created_at END ASC,
  CASE WHEN $6::text = 'occurred' AND $7::text = 'desc' THEN e.created_at END DESC,
  CASE WHEN $6::text = 'amount' AND $7::text = 'asc' THEN e.base_amount_minor END ASC,
  CASE WHEN $6::text = 'amount' AND $7::text = 'desc' THEN e.base_amount_minor END DESC,
  CASE WHEN $6::text = 'type' AND $7::text = 'asc' THEN e.event_type END ASC,
  CASE WHEN $6::text = 'type' AND $7::text = 'desc' THEN e.event_type END DESC,
  e.created_at DESC, e.id DESC
LIMIT $9::bigint OFFSET $8::bigint
`

type ListAssetEventsPageParams struct {
	TenantID        uuid.UUID
	AssetID         uuid.UUID
	ShowVoided      bool
	SearchQuery     string
	EventTypeFilter string
	SortKey         string
	SortDirection   string
	PageOffset      int64
	PageSize        int64
}

type ListAssetEventsPageRow struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	AssetID             uuid.UUID
	TransactionID       uuid.UUID
	EventType           string
	BaseAmountMinor     int64
	BaseCurrency        string
	OriginalAmountMinor sql.NullInt64
	OriginalCurrency    sql.NullString
	FxRateScaled        sql.NullInt64
	FxRateDate          sql.NullTime
	FxRateSource        sql.NullString
	Notes               string
	VoidsEventID        uuid.NullUUID
	ReplacesEventID     uuid.NullUUID
	OccurredAt          time.Time
	CreatedByUserID     uuid.UUID
	CreatedAt           time.Time
	IsVoided            bool
	TotalCount          int64
}

func (q *Queries) ListAssetEventsPage(ctx context.Context, arg ListAssetEventsPageParams) ([]ListAssetEventsPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetEventsPage,
		arg.TenantID,
		arg.AssetID,
		arg.ShowVoided,
		arg.SearchQuery,
		arg.EventTypeFilter,
		arg.SortKey,
		arg.SortDirection,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetEventsPageRow
	for rows.Next() {
		var i ListAssetEventsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssetID,
			&i.TransactionID,
			&i.EventType,
			&i.BaseAmountMinor,
			&i.BaseCurrency,
			&i.OriginalAmountMinor,
			&i.OriginalCurrency,
			&i.FxRateScaled,
			&i.FxRateDate,
			&i.FxRateSource,
			&i.Notes,
			&i.VoidsEventID,
			&i.ReplacesEventID,
			&i.OccurredAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.IsVoided,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssets = `-- name: ListAssets :many
SELECT a.id, a.tenant_id, c.id AS category_id, c.name AS category_name,
       c.icon_key AS category_icon,
       m.id AS model_id, m.name AS model_name, v.id AS variant_id,
       v.name AS variant_name, a.display_name, a.serial_number, a.color,
       a.purchase_channel, a.notes, a.created_at
FROM assets a
JOIN product_variants v ON v.tenant_id = a.tenant_id AND v.id = a.variant_id
JOIN product_models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
WHERE a.tenant_id = $1
ORDER BY a.created_at DESC, a.id
`

type ListAssetsRow struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	CategoryID      uuid.UUID
	CategoryName    string
	CategoryIcon    string
	ModelID         uuid.UUID
	ModelName       string
	VariantID       uuid.UUID
	VariantName     string
	DisplayName     string
	SerialNumber    string
	Color           string
	PurchaseChannel string
	Notes           string
	CreatedAt       time.Time
}

func (q *Queries) ListAssets(ctx context.Context, tenantID uuid.UUID) ([]ListAssetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssets, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsRow
	for rows.Next() {
		var i ListAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.ModelID,
			&i.ModelName,
			&i.VariantID,
			&i.VariantName,
			&i.DisplayName,
			&i.SerialNumber,
			&i.Color,
			&i.PurchaseChannel,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsWithSummary = `-- name: ListAssetsWithSummary :many
WITH effective_events AS (
SELECT e.id, e.tenant_id, e.asset_id, e.transaction_id, e.event_type, e.base_amount_minor, e.base_currency, e.original_amount_minor, e.original_currency, e.fx_rate_scaled, e.fx_rate_date, e.fx_rate_source, e.notes, e.voids_event_id, e.replaces_event_id, e.occurred_at, e.created_by_user_id, e.created_at
FROM asset_events e
WHERE e.tenant_id = $6
  AND e.event_type != 'void'
  AND NOT EXISTS (
      SELECT 1 FROM asset_events void_event
      WHERE void_event.tenant_id = e.tenant_id AND void_event.voids_event_id = e.id
  )
),
event_rollup AS (
SELECT asset_id,
       SUM(CASE WHEN base_amount_minor < 0 THEN -base_amount_minor ELSE 0 END)::bigint AS expense_minor,
       SUM(CASE WHEN base_amount_minor > 0 THEN base_amount_minor ELSE 0 END)::bigint AS income_minor,
       SUM(base_amount_minor)::bigint AS net_minor,
       BOOL_OR(event_type = 'purchase') AS has_purchase,
       BOOL_OR(event_type = 'sale') AS has_sale
FROM effective_events
GROUP BY asset_id
),
ranked_events AS (
SELECT asset_id, event_type,
       ROW_NUMBER() OVER (PARTITION BY asset_id ORDER BY occurred_at DESC, created_at DESC, id DESC) AS event_rank
FROM effective_events
WHERE event_type IN ('purchase', 'repair', 'sale')
),
asset_rows AS (
SELECT a.id, a.tenant_id, c.id AS category_id, c.name AS category_name,
       c.icon_key AS category_icon,
       m.id AS model_id, m.name AS model_name, v.id AS variant_id,
       v.name AS variant_name, a.display_name, a.serial_number, a.color,
       a.purchase_channel, a.notes, a.created_at,
       COALESCE(er.expense_minor, 0)::bigint AS expense_minor,
       COALESCE(er.income_minor, 0)::bigint AS income_minor,
       COALESCE(er.net_minor, 0)::bigint AS net_minor,
       COALESCE(er.has_purchase, FALSE) AS has_purchase,
       COALESCE(er.has_sale, FALSE) AS has_sale,
       COALESCE(re.event_type, '') AS latest_event_type,
       CASE
           WHEN COALESCE(er.has_sale, FALSE) THEN 'sold'
           WHEN COALESCE(er.has_purchase, FALSE) AND re.event_type = 'repair' THEN 'repairing'
           WHEN COALESCE(er.has_purchase, FALSE) THEN 'active'
           ELSE 'unacquired'
       END::text AS status,
       t.base_currency::text AS base_currency
FROM assets a
JOIN product_variants v ON v.tenant_id = a.tenant_id AND v.id = a.variant_id
JOIN product_models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
JOIN tenants t ON t.id = a.tenant_id
LEFT JOIN event_rollup er ON er.asset_id = a.id
LEFT JOIN ranked_events re ON re.asset_id = a.id AND re.event_rank = 1
WHERE a.tenant_id = $6
  AND ($7::text = '' OR (
       a.display_name ILIKE '%' || $7::text || '%' OR
       a.serial_number ILIKE '%' || $7::text || '%' OR
       a.color ILIKE '%' || $7::text || '%' OR
       a.purchase_channel ILIKE '%' || $7::text || '%' OR
       a.notes ILIKE '%' || $7::text || '%' OR
       m.name ILIKE '%' || $7::text || '%' OR
       v.name ILIKE '%' || $7::text || '%' OR
       c.name ILIKE '%' || $7::text || '%'
  ))
)
SELECT id, tenant_id, category_id, category_name, category_icon, model_id, model_name,
       variant_id, variant_name, display_name, serial_number, color, purchase_channel, notes, created_at,
       expense_minor, income_minor, net_minor,
       status,
       base_currency
FROM asset_rows
WHERE $1::text IN ('', 'all')
   OR ($1::text = 'sold' AND has_sale)
   OR ($1::text = 'repairing' AND NOT has_sale AND has_purchase AND latest_event_type = 'repair')
   OR ($1::text = 'active' AND NOT has_sale AND has_purchase AND latest_event_type != 'repair')
   OR ($1::text = 'unacquired' AND NOT has_sale AND NOT has_purchase)
ORDER BY
  CASE WHEN $2::text = 'name' AND $3::text = 'asc' THEN LOWER(display_name) END ASC,
  CASE WHEN $2::text = 'name' AND $3::text = 'desc' THEN LOWER(display_name) END DESC,
  CASE WHEN $2::text = 'model' AND $3::text = 'asc' THEN LOWER(model_name || ' ' || variant_name) END ASC,
  CASE WHEN $2::text = 'model' AND $3::text = 'desc' THEN LOWER(model_name || ' ' || variant_name) END DESC,
  CASE WHEN $2::text = 'status' AND $3::text = 'asc' THEN status END ASC,
  CASE WHEN $2::text = 'status' AND $3::text = 'desc' THEN status END DESC,
  CASE WHEN $2::text = 'net' AND $3::text = 'asc' THEN net_minor END ASC,
  CASE WHEN $2::text = 'net' AND $3::text = 'desc' THEN net_minor END DESC,
  CASE WHEN $2::text = 'cost' AND $3::text = 'asc' THEN expense_minor END ASC,
  CASE WHEN $2::text = 'cost' AND $3::text = 'desc' THEN expense_minor END DESC,
  CASE WHEN $2::text = 'created' AND $3::text = 'asc' THEN created_at END ASC,
  CASE WHEN $2::text = 'created' AND $3::text = 'desc' THEN created_at END DESC,
  id
LIMIT $5::bigint OFFSET $4::bigint
`

type ListAssetsWithSummaryParams struct {
	StatusFilter  string
	SortKey       string
	SortDirection string
	PageOffset    int64
	PageSize      int64
	TenantID      uuid.UUID
	SearchQuery   string
}

type ListAssetsWithSummaryRow struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	CategoryID      uuid.UUID
	CategoryName    string
	CategoryIcon    string
	ModelID         uuid.UUID
	ModelName       string
	VariantID       uuid.UUID
	VariantName     string
	DisplayName     string
	SerialNumber    string
	Color           string
	PurchaseChannel string
	Notes           string
	CreatedAt       time.Time
	ExpenseMinor    int64
	IncomeMinor     int64
	NetMinor        int64
	Status          string
	BaseCurrency    string
}

func (q *Queries) ListAssetsWithSummary(ctx context.Context, arg ListAssetsWithSummaryParams) ([]ListAssetsWithSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsWithSummary,
		arg.StatusFilter,
		arg.SortKey,
		arg.SortDirection,
		arg.PageOffset,
		arg.PageSize,
		arg.TenantID,
		arg.SearchQuery,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsWithSummaryRow
	for rows.Next() {
		var i ListAssetsWithSummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.ModelID,
			&i.ModelName,
			&i.VariantID,
			&i.VariantName,
			&i.DisplayName,
			&i.SerialNumber,
			&i.Color,
			&i.PurchaseChannel,
			&i.Notes,
			&i.CreatedAt,
			&i.ExpenseMinor,
			&i.IncomeMinor,
			&i.NetMinor,
			&i.Status,
			&i.BaseCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, tenant_id, name, icon_key, created_at
FROM item_categories
WHERE tenant_id = $1
ORDER BY name, id
`

type ListCategoriesRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	IconKey   string
	CreatedAt time.Time
}

func (q *Queries) ListCategories(ctx context.Context, tenantID uuid.UUID) ([]ListCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.IconKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT u.id AS user_id, u.username, tm.role, tm.created_at
FROM tenant_memberships tm
JOIN users u ON u.id = tm.user_id
WHERE tm.tenant_id = $1
ORDER BY u.username_normalized
`

type ListMembersRow struct {
	UserID    uuid.UUID
	Username  string
	Role      string
	CreatedAt time.Time
}

func (q *Queries) ListMembers(ctx context.Context, tenantID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersPage = `-- name: ListMembersPage :many
SELECT u.id AS user_id, u.username, tm.role, tm.created_at, COUNT(*) OVER () AS total_count
FROM tenant_memberships tm
JOIN users u ON u.id = tm.user_id
WHERE tm.tenant_id = $1
  AND ($2::text = '' OR u.username ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR tm.role = $3::text)
ORDER BY
  CASE WHEN $4::text = 'username' AND $5::text = 'asc' THEN u.username_normalized END ASC,
  CASE WHEN $4::text = 'username' AND $5::text = 'desc' THEN u.username_normalized END DESC,
  CASE WHEN $4::text = 'role' AND $5::text = 'asc' THEN tm.role END ASC,
  CASE WHEN $4::text = 'role' AND $5::text = 'desc' THEN tm.role END DESC,
  CASE WHEN $4::text = 'created' AND $5::text = 'asc' THEN tm.created_at END ASC,
  CASE WHEN $4::text = 'created' AND $5::text = 'desc' THEN tm.created_at END DESC,
  u.id
LIMIT $7::bigint OFFSET $6::bigint
`

type ListMembersPageParams struct {
	TenantID      uuid.UUID
	SearchQuery   string
	RoleFilter    string
	SortKey       string
	SortDirection string
	PageOffset    int64
	PageSize      int64
}

type ListMembersPageRow struct {
	UserID     uuid.UUID
	Username   string
	Role       string
	CreatedAt  time.Time
	TotalCount int64
}

func (q *Queries) ListMembersPage(ctx context.Context, arg ListMembersPageParams) ([]ListMembersPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembersPage,
		arg.TenantID,
		arg.SearchQuery,
		arg.RoleFilter,
		arg.SortKey,
		arg.SortDirection,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersPageRow
	for rows.Next() {
		var i ListMembersPageRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Role,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many
SELECT m.id, m.tenant_id, m.category_id, c.name AS category_name, c.icon_key AS category_icon, m.name, m.created_at
FROM product_models m
JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
WHERE m.tenant_id = $1
ORDER BY c.name, m.name, m.id
`

type ListModelsRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	CategoryID   uuid.UUID
	CategoryName string
	CategoryIcon string
	Name         string
	CreatedAt    time.Time
}

func (q *Queries) ListModels(ctx context.Context, tenantID uuid.UUID) ([]ListModelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listModels, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelsRow
	for rows.Next() {
		var i ListModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsWithVariants = `-- name: ListModelsWithVariants :many
WITH filtered_models AS (
    SELECT m.id, m.tenant_id, m.category_id, c.name AS category_name,
           c.icon_key AS category_icon, m.name, m.created_at
    FROM product_models m
    JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
    WHERE m.tenant_id = $1
      AND ($2::text = '' OR m.name ILIKE '%' || $2::text || '%' OR c.name ILIKE '%' || $2::text || '%')
      AND ($3::text = '' OR m.category_id::text = $3::text)
),
paged_models AS (
    SELECT id, tenant_id, category_id, category_name, category_icon, name, created_at, COUNT(*) OVER () AS total_count,
           ROW_NUMBER() OVER (ORDER BY
             CASE WHEN $4::text = 'category' AND $5::text = 'asc' THEN LOWER(category_name) END ASC,
             CASE WHEN $4::text = 'category' AND $5::text = 'desc' THEN LOWER(category_name) END DESC,
             CASE WHEN $4::text = 'name' AND $5::text = 'asc' THEN LOWER(name) END ASC,
             CASE WHEN $4::text = 'name' AND $5::text = 'desc' THEN LOWER(name) END DESC,
             CASE WHEN $4::text = 'created' AND $5::text = 'asc' THEN created_at END ASC,
             CASE WHEN $4::text = 'created' AND $5::text = 'desc' THEN created_at END DESC,
             LOWER(category_name), LOWER(name), id) AS page_order
    FROM filtered_models
    LIMIT $7::bigint OFFSET $6::bigint
)
SELECT pm.id, pm.tenant_id, pm.category_id, pm.category_name, pm.category_icon,
       pm.name, pm.created_at, pm.total_count, pm.page_order,
       v.id AS variant_id, v.name AS variant_name, v.created_at AS variant_created_at
FROM paged_models pm
LEFT JOIN product_variants v ON v.tenant_id = pm.tenant_id AND v.model_id = pm.id
ORDER BY pm.page_order, LOWER(v.name), v.id
`

type ListModelsWithVariantsParams struct {
	TenantID       uuid.UUID
	SearchQuery    string
	CategoryFilter string
	SortKey        string
	SortDirection  string
	PageOffset     int64
	PageSize       int64
}

type ListModelsWithVariantsRow struct {
	ID               uuid.UUID
	TenantID         uuid.UUID
	CategoryID       uuid.UUID
	CategoryName     string
	CategoryIcon     string
	Name             string
	CreatedAt        time.Time
	TotalCount       int64
	PageOrder        int64
	VariantID        uuid.NullUUID
	VariantName      sql.NullString
	VariantCreatedAt sql.NullTime
}

func (q *Queries) ListModelsWithVariants(ctx context.Context, arg ListModelsWithVariantsParams) ([]ListModelsWithVariantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listModelsWithVariants,
		arg.TenantID,
		arg.SearchQuery,
		arg.CategoryFilter,
		arg.SortKey,
		arg.SortDirection,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelsWithVariantsRow
	for rows.Next() {
		var i ListModelsWithVariantsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.Name,
			&i.CreatedAt,
			&i.TotalCount,
			&i.PageOrder,
			&i.VariantID,
			&i.VariantName,
			&i.VariantCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariants = `-- name: ListVariants :many
SELECT v.id, v.tenant_id, m.category_id, c.name AS category_name,
       c.icon_key AS category_icon, v.model_id, m.name AS model_name, v.name, v.created_at
FROM product_variants v
JOIN product_models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
WHERE v.tenant_id = $1
ORDER BY c.name, m.name, v.name, v.id
`

type ListVariantsRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	CategoryID   uuid.UUID
	CategoryName string
	CategoryIcon string
	ModelID      uuid.UUID
	ModelName    string
	Name         string
	CreatedAt    time.Time
}

func (q *Queries) ListVariants(ctx context.Context, tenantID uuid.UUID) ([]ListVariantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVariants, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVariantsRow
	for rows.Next() {
		var i ListVariantsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.ModelID,
			&i.ModelName,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLifecycleTenant = `-- name: LockLifecycleTenant :execrows
UPDATE tenants SET id = id WHERE id = $1
`

func (q *Queries) LockLifecycleTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockLifecycleTenant, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const lockTenantBaseCurrency = `-- name: LockTenantBaseCurrency :exec
UPDATE tenants
SET base_currency_locked = TRUE
WHERE id = $1 AND base_currency = $2
`

type LockTenantBaseCurrencyParams struct {
	ID           uuid.UUID
	BaseCurrency string
}

func (q *Queries) LockTenantBaseCurrency(ctx context.Context, arg LockTenantBaseCurrencyParams) error {
	_, err := q.db.ExecContext(ctx, lockTenantBaseCurrency, arg.ID, arg.BaseCurrency)
	return err
}

const saveLifecycleRequest = `-- name: SaveLifecycleRequest :exec
INSERT INTO lifecycle_requests (tenant_id, user_id, request_key, request_hash, event_id)
VALUES ($1, $2, $3, $4, $5)
`

type SaveLifecycleRequestParams struct {
	TenantID    uuid.UUID
	UserID      uuid.UUID
	RequestKey  string
	RequestHash string
	EventID     uuid.UUID
}

func (q *Queries) SaveLifecycleRequest(ctx context.Context, arg SaveLifecycleRequestParams) error {
	_, err := q.db.ExecContext(ctx, saveLifecycleRequest,
		arg.TenantID,
		arg.UserID,
		arg.RequestKey,
		arg.RequestHash,
		arg.EventID,
	)
	return err
}

const updateCatalogAsset = `-- name: UpdateCatalogAsset :execrows
UPDATE assets
SET variant_id = $1, display_name = $2, serial_number = $3, color = $4, purchase_channel = $5, notes = $6
WHERE tenant_id = $7 AND id = $8
`

type UpdateCatalogAssetParams struct {
	VariantID       uuid.UUID
	DisplayName     string
	SerialNumber    string
	Color           string
	PurchaseChannel string
	Notes           string
	TenantID        uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) UpdateCatalogAsset(ctx context.Context, arg UpdateCatalogAssetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCatalogAsset,
		arg.VariantID,
		arg.DisplayName,
		arg.SerialNumber,
		arg.Color,
		arg.PurchaseChannel,
		arg.Notes,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCategory = `-- name: UpdateCategory :execrows
UPDATE item_categories
SET name = $1, icon_key = $2
WHERE tenant_id = $3 AND id = $4
`

type UpdateCategoryParams struct {
	Name     string
	IconKey  string
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCategory,
		arg.Name,
		arg.IconKey,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateModel = `-- name: UpdateModel :execrows
UPDATE product_models
SET category_id = $1, name = $2
WHERE tenant_id = $3 AND id = $4
`

type UpdateModelParams struct {
	CategoryID uuid.UUID
	Name       string
	TenantID   uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateModel,
		arg.CategoryID,
		arg.Name,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserPreferences = `-- name: UpdateUserPreferences :exec
UPDATE users SET locale = $1, theme = $2, accent = $3 WHERE id = $4
`

type UpdateUserPreferencesParams struct {
	Locale string
	Theme  string
	Accent string
	ID     uuid.UUID
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPreferences,
		arg.Locale,
		arg.Theme,
		arg.Accent,
		arg.ID,
	)
	return err
}

const updateVariant = `-- name: UpdateVariant :execrows
UPDATE product_variants
SET model_id = $1, name = $2
WHERE tenant_id = $3 AND id = $4
`

type UpdateVariantParams struct {
	ModelID  uuid.UUID
	Name     string
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVariant,
		arg.ModelID,
		arg.Name,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
