// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package postgresdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAsset = `-- name: CreateAsset :exec
INSERT INTO assets (id, tenant_id, variant_id, display_name, created_at) VALUES ($1, $2, $3, $4, $5)
`

type CreateAssetParams struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	VariantID   uuid.UUID
	DisplayName string
	CreatedAt   time.Time
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) error {
	_, err := q.db.ExecContext(ctx, createAsset,
		arg.ID,
		arg.TenantID,
		arg.VariantID,
		arg.DisplayName,
		arg.CreatedAt,
	)
	return err
}

const ensureCategory = `-- name: EnsureCategory :one
INSERT INTO item_categories (id, tenant_id, name, created_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, name) DO UPDATE SET name = excluded.name
RETURNING id
`

type EnsureCategoryParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) EnsureCategory(ctx context.Context, arg EnsureCategoryParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, ensureCategory,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const ensureModel = `-- name: EnsureModel :one
INSERT INTO product_models (id, tenant_id, category_id, name, created_at) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, category_id, name) DO UPDATE SET name = excluded.name
RETURNING id
`

type EnsureModelParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	CategoryID uuid.UUID
	Name       string
	CreatedAt  time.Time
}

func (q *Queries) EnsureModel(ctx context.Context, arg EnsureModelParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, ensureModel,
		arg.ID,
		arg.TenantID,
		arg.CategoryID,
		arg.Name,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const ensureTenant = `-- name: EnsureTenant :exec
INSERT INTO tenants (id, name, base_currency, created_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO NOTHING
`

type EnsureTenantParams struct {
	ID           uuid.UUID
	Name         string
	BaseCurrency string
	CreatedAt    time.Time
}

func (q *Queries) EnsureTenant(ctx context.Context, arg EnsureTenantParams) error {
	_, err := q.db.ExecContext(ctx, ensureTenant,
		arg.ID,
		arg.Name,
		arg.BaseCurrency,
		arg.CreatedAt,
	)
	return err
}

const ensureVariant = `-- name: EnsureVariant :one
INSERT INTO product_variants (id, tenant_id, model_id, name, created_at) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, model_id, name) DO UPDATE SET name = excluded.name
RETURNING id
`

type EnsureVariantParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	ModelID   uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) EnsureVariant(ctx context.Context, arg EnsureVariantParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, ensureVariant,
		arg.ID,
		arg.TenantID,
		arg.ModelID,
		arg.Name,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAsset = `-- name: GetAsset :one
SELECT a.id, a.tenant_id, c.id AS category_id, c.name AS category_name,
       m.id AS model_id, m.name AS model_name, v.id AS variant_id,
       v.name AS variant_name, a.display_name, a.created_at
FROM assets a
JOIN product_variants v ON v.tenant_id = a.tenant_id AND v.id = a.variant_id
JOIN product_models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
WHERE a.tenant_id = $1 AND a.id = $2
`

type GetAssetParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetAssetRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	CategoryID   uuid.UUID
	CategoryName string
	ModelID      uuid.UUID
	ModelName    string
	VariantID    uuid.UUID
	VariantName  string
	DisplayName  string
	CreatedAt    time.Time
}

func (q *Queries) GetAsset(ctx context.Context, arg GetAssetParams) (GetAssetRow, error) {
	row := q.db.QueryRowContext(ctx, getAsset, arg.TenantID, arg.ID)
	var i GetAssetRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.CategoryName,
		&i.ModelID,
		&i.ModelName,
		&i.VariantID,
		&i.VariantName,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}
