// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package sqlitedb

import (
	"context"
)

const clearModelImage = `-- name: ClearModelImage :exec
UPDATE model_images SET active=0 WHERE tenant_id=? AND model_id=? AND active=1
`

type ClearModelImageParams struct {
	TenantID string
	ModelID  string
}

func (q *Queries) ClearModelImage(ctx context.Context, arg ClearModelImageParams) error {
	_, err := q.db.ExecContext(ctx, clearModelImage, arg.TenantID, arg.ModelID)
	return err
}

const getImageRevision = `-- name: GetImageRevision :one
SELECT id, tenant_id, model_id, store_id, object_key, sha256, content_type, size_bytes, source_url, active FROM model_images WHERE tenant_id=? AND id=?
`

type GetImageRevisionParams struct {
	TenantID string
	ID       string
}

func (q *Queries) GetImageRevision(ctx context.Context, arg GetImageRevisionParams) (ModelImage, error) {
	row := q.db.QueryRowContext(ctx, getImageRevision, arg.TenantID, arg.ID)
	var i ModelImage
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ModelID,
		&i.StoreID,
		&i.ObjectKey,
		&i.Sha256,
		&i.ContentType,
		&i.SizeBytes,
		&i.SourceUrl,
		&i.Active,
	)
	return i, err
}

const getModelImage = `-- name: GetModelImage :one
SELECT id, tenant_id, model_id, store_id, object_key, sha256, content_type, size_bytes, source_url, active FROM model_images WHERE tenant_id=? AND model_id=? AND active=1
`

type GetModelImageParams struct {
	TenantID string
	ModelID  string
}

func (q *Queries) GetModelImage(ctx context.Context, arg GetModelImageParams) (ModelImage, error) {
	row := q.db.QueryRowContext(ctx, getModelImage, arg.TenantID, arg.ModelID)
	var i ModelImage
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ModelID,
		&i.StoreID,
		&i.ObjectKey,
		&i.Sha256,
		&i.ContentType,
		&i.SizeBytes,
		&i.SourceUrl,
		&i.Active,
	)
	return i, err
}

const insertModelImage = `-- name: InsertModelImage :exec
INSERT INTO model_images(id,tenant_id,model_id,store_id,object_key,sha256,content_type,size_bytes,source_url,active)
VALUES (?,?,?,?,?,?,?,?,?,1)
`

type InsertModelImageParams struct {
	ID          string
	TenantID    string
	ModelID     string
	StoreID     string
	ObjectKey   string
	Sha256      string
	ContentType string
	SizeBytes   int64
	SourceUrl   string
}

func (q *Queries) InsertModelImage(ctx context.Context, arg InsertModelImageParams) error {
	_, err := q.db.ExecContext(ctx, insertModelImage,
		arg.ID,
		arg.TenantID,
		arg.ModelID,
		arg.StoreID,
		arg.ObjectKey,
		arg.Sha256,
		arg.ContentType,
		arg.SizeBytes,
		arg.SourceUrl,
	)
	return err
}
