// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: management.sql

package sqlitedb

import (
	"context"
)

const findManagementRequest = `-- name: FindManagementRequest :one
SELECT request_hash, result_json FROM management_requests
WHERE tenant_id = ?1 AND user_id = ?2 AND request_key = ?3
`

type FindManagementRequestParams struct {
	TenantID   string
	UserID     string
	RequestKey string
}

type FindManagementRequestRow struct {
	RequestHash string
	ResultJson  string
}

func (q *Queries) FindManagementRequest(ctx context.Context, arg FindManagementRequestParams) (FindManagementRequestRow, error) {
	row := q.db.QueryRowContext(ctx, findManagementRequest, arg.TenantID, arg.UserID, arg.RequestKey)
	var i FindManagementRequestRow
	err := row.Scan(&i.RequestHash, &i.ResultJson)
	return i, err
}

const saveManagementRequest = `-- name: SaveManagementRequest :exec
INSERT INTO management_requests (tenant_id,user_id,request_key,request_hash,result_json)
VALUES (?1,?2,?3,?4,?5)
`

type SaveManagementRequestParams struct {
	TenantID    string
	UserID      string
	RequestKey  string
	RequestHash string
	ResultJson  string
}

func (q *Queries) SaveManagementRequest(ctx context.Context, arg SaveManagementRequestParams) error {
	_, err := q.db.ExecContext(ctx, saveManagementRequest,
		arg.TenantID,
		arg.UserID,
		arg.RequestKey,
		arg.RequestHash,
		arg.ResultJson,
	)
	return err
}
