// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: market.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const bindAssetMarket = `-- name: BindAssetMarket :exec
INSERT INTO asset_market_bindings(tenant_id,asset_id,market_item_id) VALUES(CAST(?1 AS TEXT),CAST(?2 AS TEXT),?3) ON CONFLICT(tenant_id,asset_id) DO UPDATE SET market_item_id=excluded.market_item_id
`

type BindAssetMarketParams struct {
	Tenant       string
	AssetID      string
	MarketItemID string
}

func (q *Queries) BindAssetMarket(ctx context.Context, arg BindAssetMarketParams) error {
	_, err := q.db.ExecContext(ctx, bindAssetMarket, arg.Tenant, arg.AssetID, arg.MarketItemID)
	return err
}

const claimMarketLease = `-- name: ClaimMarketLease :execrows
UPDATE market_items SET lease_token=?1,lease_until=?2,last_attempt=?3 WHERE CAST(tenant_id AS TEXT)=CAST(?4 AS TEXT) AND id=?5 AND enabled=1 AND lease_until<=?3
`

type ClaimMarketLeaseParams struct {
	Token     string
	UntilTime int64
	NowTime   int64
	Tenant    string
	ID        string
}

func (q *Queries) ClaimMarketLease(ctx context.Context, arg ClaimMarketLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimMarketLease,
		arg.Token,
		arg.UntilTime,
		arg.NowTime,
		arg.Tenant,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createMarketItem = `-- name: CreateMarketItem :exec
INSERT INTO market_items(id,tenant_id,name,provider,keyword,filter_criteria,model_desc,region,external_id,enabled,created_at,last_success) VALUES(?1,CAST(?2 AS TEXT),?3,?4,?5,?6,?7,?8,?9,?10,?11,?12)
`

type CreateMarketItemParams struct {
	ID             string
	Tenant         string
	Name           string
	Provider       string
	Keyword        string
	FilterCriteria string
	ModelDesc      string
	Region         string
	ExternalID     sql.NullString
	Enabled        int64
	CreatedAt      int64
	LastSuccess    int64
}

func (q *Queries) CreateMarketItem(ctx context.Context, arg CreateMarketItemParams) error {
	_, err := q.db.ExecContext(ctx, createMarketItem,
		arg.ID,
		arg.Tenant,
		arg.Name,
		arg.Provider,
		arg.Keyword,
		arg.FilterCriteria,
		arg.ModelDesc,
		arg.Region,
		arg.ExternalID,
		arg.Enabled,
		arg.CreatedAt,
		arg.LastSuccess,
	)
	return err
}

const finishMarketLease = `-- name: FinishMarketLease :execrows
UPDATE market_items SET lease_token='',lease_until=0,last_error=?1,last_success=CASE WHEN ?1='' THEN ?2 ELSE last_success END WHERE CAST(tenant_id AS TEXT)=CAST(?3 AS TEXT) AND id=?4 AND lease_token=?5
`

type FinishMarketLeaseParams struct {
	LastError   string
	SuccessTime int64
	Tenant      string
	ID          string
	Token       string
}

func (q *Queries) FinishMarketLease(ctx context.Context, arg FinishMarketLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishMarketLease,
		arg.LastError,
		arg.SuccessTime,
		arg.Tenant,
		arg.ID,
		arg.Token,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMarketItem = `-- name: GetMarketItem :one
SELECT id, CAST(tenant_id AS TEXT) AS tenant_id, name,provider,keyword,filter_criteria,model_desc,region,external_id,enabled,created_at,last_attempt,last_success,last_error,lease_token,lease_until FROM market_items WHERE CAST(tenant_id AS TEXT)=CAST(?1 AS TEXT) AND id=?2
`

type GetMarketItemParams struct {
	Tenant string
	ID     string
}

type GetMarketItemRow struct {
	ID             string
	TenantID       string
	Name           string
	Provider       string
	Keyword        string
	FilterCriteria string
	ModelDesc      string
	Region         string
	ExternalID     sql.NullString
	Enabled        int64
	CreatedAt      int64
	LastAttempt    int64
	LastSuccess    int64
	LastError      string
	LeaseToken     string
	LeaseUntil     int64
}

func (q *Queries) GetMarketItem(ctx context.Context, arg GetMarketItemParams) (GetMarketItemRow, error) {
	row := q.db.QueryRowContext(ctx, getMarketItem, arg.Tenant, arg.ID)
	var i GetMarketItemRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Provider,
		&i.Keyword,
		&i.FilterCriteria,
		&i.ModelDesc,
		&i.Region,
		&i.ExternalID,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastAttempt,
		&i.LastSuccess,
		&i.LastError,
		&i.LeaseToken,
		&i.LeaseUntil,
	)
	return i, err
}

const listMarketItems = `-- name: ListMarketItems :many
SELECT id, CAST(tenant_id AS TEXT) AS tenant_id, name,provider,keyword,filter_criteria,model_desc,region,external_id,enabled,created_at,last_attempt,last_success,last_error,lease_token,lease_until FROM market_items WHERE CAST(tenant_id AS TEXT)=CAST(?1 AS TEXT) ORDER BY name,id
`

type ListMarketItemsRow struct {
	ID             string
	TenantID       string
	Name           string
	Provider       string
	Keyword        string
	FilterCriteria string
	ModelDesc      string
	Region         string
	ExternalID     sql.NullString
	Enabled        int64
	CreatedAt      int64
	LastAttempt    int64
	LastSuccess    int64
	LastError      string
	LeaseToken     string
	LeaseUntil     int64
}

func (q *Queries) ListMarketItems(ctx context.Context, tenant string) ([]ListMarketItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMarketItems, tenant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMarketItemsRow
	for rows.Next() {
		var i ListMarketItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Provider,
			&i.Keyword,
			&i.FilterCriteria,
			&i.ModelDesc,
			&i.Region,
			&i.ExternalID,
			&i.Enabled,
			&i.CreatedAt,
			&i.LastAttempt,
			&i.LastSuccess,
			&i.LastError,
			&i.LeaseToken,
			&i.LeaseUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketPrices = `-- name: ListMarketPrices :many
SELECT CAST(tenant_id AS TEXT) AS tenant_id,market_item_id,observation_date,observed_at,max_minor,min_minor,currency,base_currency,base_minor,rate_scaled,rate_date,rate_source,provider,provider_version,provenance,evidence,source_date,sample_count FROM market_prices WHERE CAST(tenant_id AS TEXT)=CAST(?1 AS TEXT) AND market_item_id=?2 ORDER BY observation_date DESC
`

type ListMarketPricesParams struct {
	Tenant string
	ID     string
}

type ListMarketPricesRow struct {
	TenantID        string
	MarketItemID    string
	ObservationDate string
	ObservedAt      int64
	MaxMinor        int64
	MinMinor        sql.NullInt64
	Currency        string
	BaseCurrency    string
	BaseMinor       sql.NullInt64
	RateScaled      sql.NullInt64
	RateDate        sql.NullString
	RateSource      sql.NullString
	Provider        string
	ProviderVersion string
	Provenance      string
	Evidence        string
	SourceDate      sql.NullString
	SampleCount     sql.NullInt64
}

func (q *Queries) ListMarketPrices(ctx context.Context, arg ListMarketPricesParams) ([]ListMarketPricesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMarketPrices, arg.Tenant, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMarketPricesRow
	for rows.Next() {
		var i ListMarketPricesRow
		if err := rows.Scan(
			&i.TenantID,
			&i.MarketItemID,
			&i.ObservationDate,
			&i.ObservedAt,
			&i.MaxMinor,
			&i.MinMinor,
			&i.Currency,
			&i.BaseCurrency,
			&i.BaseMinor,
			&i.RateScaled,
			&i.RateDate,
			&i.RateSource,
			&i.Provider,
			&i.ProviderVersion,
			&i.Provenance,
			&i.Evidence,
			&i.SourceDate,
			&i.SampleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarketTenants = `-- name: ListMarketTenants :many
SELECT DISTINCT CAST(tenant_id AS TEXT) AS tenant FROM market_items ORDER BY tenant
`

func (q *Queries) ListMarketTenants(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMarketTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tenant string
		if err := rows.Scan(&tenant); err != nil {
			return nil, err
		}
		items = append(items, tenant)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketAssetIDs = `-- name: MarketAssetIDs :many
SELECT CAST(asset_id AS TEXT) AS asset_id FROM asset_market_bindings WHERE CAST(tenant_id AS TEXT)=CAST(?1 AS TEXT) AND market_item_id=?2 ORDER BY asset_id
`

type MarketAssetIDsParams struct {
	Tenant string
	ID     string
}

func (q *Queries) MarketAssetIDs(ctx context.Context, arg MarketAssetIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, marketAssetIDs, arg.Tenant, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var asset_id string
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putMarketPrice = `-- name: PutMarketPrice :exec
INSERT INTO market_prices(tenant_id,market_item_id,observation_date,observed_at,max_minor,min_minor,currency,base_currency,base_minor,rate_scaled,rate_date,rate_source,provider,provider_version,provenance,evidence,source_date,sample_count)
VALUES(CAST(?1 AS TEXT),?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16,?17,?18)
ON CONFLICT(tenant_id,market_item_id,observation_date) DO UPDATE SET observed_at=excluded.observed_at,max_minor=excluded.max_minor,min_minor=excluded.min_minor,currency=excluded.currency,base_currency=excluded.base_currency,base_minor=excluded.base_minor,rate_scaled=excluded.rate_scaled,rate_date=excluded.rate_date,rate_source=excluded.rate_source,provider=excluded.provider,provider_version=excluded.provider_version,provenance=excluded.provenance,evidence=excluded.evidence,source_date=excluded.source_date,sample_count=excluded.sample_count
WHERE excluded.observed_at >= market_prices.observed_at
`

type PutMarketPriceParams struct {
	Tenant          string
	MarketItemID    string
	ObservationDate string
	ObservedAt      int64
	MaxMinor        int64
	MinMinor        sql.NullInt64
	Currency        string
	BaseCurrency    string
	BaseMinor       sql.NullInt64
	RateScaled      sql.NullInt64
	RateDate        sql.NullString
	RateSource      sql.NullString
	Provider        string
	ProviderVersion string
	Provenance      string
	Evidence        string
	SourceDate      sql.NullString
	SampleCount     sql.NullInt64
}

func (q *Queries) PutMarketPrice(ctx context.Context, arg PutMarketPriceParams) error {
	_, err := q.db.ExecContext(ctx, putMarketPrice,
		arg.Tenant,
		arg.MarketItemID,
		arg.ObservationDate,
		arg.ObservedAt,
		arg.MaxMinor,
		arg.MinMinor,
		arg.Currency,
		arg.BaseCurrency,
		arg.BaseMinor,
		arg.RateScaled,
		arg.RateDate,
		arg.RateSource,
		arg.Provider,
		arg.ProviderVersion,
		arg.Provenance,
		arg.Evidence,
		arg.SourceDate,
		arg.SampleCount,
	)
	return err
}

const unbindAssetMarket = `-- name: UnbindAssetMarket :exec
DELETE FROM asset_market_bindings WHERE CAST(tenant_id AS TEXT)=CAST(?1 AS TEXT) AND CAST(asset_id AS TEXT)=CAST(?2 AS TEXT)
`

type UnbindAssetMarketParams struct {
	Tenant  string
	AssetID string
}

func (q *Queries) UnbindAssetMarket(ctx context.Context, arg UnbindAssetMarketParams) error {
	_, err := q.db.ExecContext(ctx, unbindAssetMarket, arg.Tenant, arg.AssetID)
	return err
}

const updateMarketItem = `-- name: UpdateMarketItem :execrows
UPDATE market_items SET name=?1,enabled=?2 WHERE CAST(tenant_id AS TEXT)=CAST(?3 AS TEXT) AND id=?4
`

type UpdateMarketItemParams struct {
	Name    string
	Enabled int64
	Tenant  string
	ID      string
}

func (q *Queries) UpdateMarketItem(ctx context.Context, arg UpdateMarketItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMarketItem,
		arg.Name,
		arg.Enabled,
		arg.Tenant,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
