// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"database/sql"
)

type Asset struct {
	ID                string
	TenantID          string
	ModelID           string
	DisplayName       string
	SerialNumber      string
	PurchaseChannel   string
	Notes             string
	CreatedAt         string
	Model3dResourceID sql.NullString
}

type AssetEvent struct {
	ID                  string
	TenantID            string
	AssetID             string
	TransactionID       string
	EventType           string
	BaseAmountMinor     int64
	BaseCurrency        string
	OriginalAmountMinor sql.NullInt64
	OriginalCurrency    sql.NullString
	FxRateScaled        sql.NullInt64
	FxRateDate          sql.NullString
	FxRateSource        sql.NullString
	Notes               string
	VoidsEventID        sql.NullString
	ReplacesEventID     sql.NullString
	OccurredAt          string
	CreatedByUserID     string
	CreatedAt           string
	EventTypeID         string
}

type AssetEventType struct {
	ID                string
	TenantID          string
	Name              string
	NormalizedName    string
	CashflowDirection string
	CreatedByUserID   string
	CreatedAt         string
	SystemCode        string
	Enabled           int64
	UpdatedAt         string
}

type AssetMarketBinding struct {
	TenantID     string
	AssetID      string
	MarketItemID string
}

type AssetSpecificationTag struct {
	TenantID string
	AssetID  string
	ModelID  string
	TagID    string
}

type AssetTransaction struct {
	ID                string
	TenantID          string
	OccurredAt        string
	Source            string
	ExternalReference string
	Notes             string
	CreatedByUserID   string
	CreatedAt         string
}

type ImportDraft struct {
	ID                     string
	TenantID               string
	AssetID                string
	EventType              string
	AmountMinor            int64
	Currency               string
	OccurredAt             string
	Source                 string
	ExternalReference      string
	Notes                  string
	RawText                string
	Status                 string
	CreatedByUserID        string
	CreatedAt              string
	ConfirmedTransactionID sql.NullString
}

type ItemCategory struct {
	ID        string
	TenantID  string
	Name      string
	CreatedAt string
	IconKey   string
}

type LifecycleRequest struct {
	TenantID    string
	UserID      string
	RequestKey  string
	RequestHash string
	EventID     string
}

type ManagementRequest struct {
	TenantID    string
	UserID      string
	RequestKey  string
	RequestHash string
	ResultJson  string
}

type MarketItem struct {
	ID             string
	TenantID       string
	Name           string
	Provider       string
	Keyword        string
	FilterCriteria string
	ModelDesc      string
	Region         string
	ExternalID     sql.NullString
	Enabled        int64
	CreatedAt      int64
	LastAttempt    int64
	LastSuccess    int64
	LastError      string
	LeaseToken     string
	LeaseUntil     int64
	SelectionJson  sql.NullString
}

type MarketPrice struct {
	TenantID        string
	MarketItemID    string
	ObservationDate string
	ObservedAt      int64
	MaxMinor        int64
	MinMinor        sql.NullInt64
	Currency        string
	BaseCurrency    string
	BaseMinor       sql.NullInt64
	RateScaled      sql.NullInt64
	RateDate        sql.NullString
	RateSource      sql.NullString
	Provider        string
	ProviderVersion string
	Provenance      string
	Evidence        string
	SourceDate      sql.NullString
	SampleCount     sql.NullInt64
}

type Model3dResource struct {
	ID        string
	TenantID  string
	Name      string
	Status    string
	StoreID   string
	ObjectKey string
	Sha256    string
	SizeBytes int64
	SourceUrl string
	Author    string
	License   string
	CreatedAt string
	UpdatedAt string
}

type ModelAllowedTag struct {
	TenantID string
	ModelID  string
	TagID    string
}

type ModelAppearanceCondition struct {
	TenantID string
	RuleID   string
	ModelID  string
	TagID    string
}

type ModelAppearanceDefault struct {
	ID         string
	TenantID   string
	ModelID    string
	ResourceID string
	CreatedAt  string
	UpdatedAt  string
}

type ModelAppearanceDimension struct {
	TenantID          string
	ModelID           string
	TypeID            string
	AffectsAppearance int64
}

type ModelImage struct {
	ID          string
	TenantID    string
	ModelID     string
	StoreID     string
	ObjectKey   string
	Sha256      string
	ContentType string
	SizeBytes   int64
	SourceUrl   string
	Active      int64
}

type OauthCredential struct {
	Hash        string
	TenantID    string
	GrantID     string
	Kind        string
	RedirectUri string
	Challenge   string
	ExpiresAt   string
	Consumed    bool
}

type OauthGrant struct {
	ID        string
	TenantID  string
	UserID    string
	ClientID  string
	Scope     string
	Resource  string
	CreatedAt string
	ExpiresAt string
	Revoked   bool
}

type ProductModel struct {
	ID                string
	TenantID          string
	CategoryID        string
	Name              string
	CreatedAt         string
	Model3dStoreID    sql.NullString
	Model3dObjectKey  sql.NullString
	Model3dSha256     sql.NullString
	Model3dSizeBytes  sql.NullInt64
	Model3dSourceUrl  sql.NullString
	Model3dAuthor     sql.NullString
	Model3dLicense    sql.NullString
	Model3dUpdatedAt  sql.NullString
	Model3dResourceID sql.NullString
}

type ResourceCategory struct {
	TenantID   string
	ResourceID string
	CategoryID string
}

type ResourceSpecificationTag struct {
	TenantID   string
	ResourceID string
	TagID      string
}

type SecurityAuditEvent struct {
	ID           string
	TenantID     string
	ActorUserID  sql.NullString
	Action       string
	TargetUserID sql.NullString
	Detail       string
	OccurredAt   string
}

type Session struct {
	TokenHash string
	TenantID  string
	UserID    string
	ExpiresAt string
	CreatedAt string
}

type SpecificationTag struct {
	ID             string
	TenantID       string
	TypeID         string
	Name           string
	NormalizedName string
	Enabled        int64
	CreatedAt      string
	UpdatedAt      string
}

type SpecificationTagType struct {
	ID                string
	TenantID          string
	Name              string
	NormalizedName    string
	Multiple          int64
	AffectsAppearance int64
	Enabled           int64
	SystemCode        string
	CreatedAt         string
	UpdatedAt         string
}

type Tenant struct {
	ID                 string
	Name               string
	BaseCurrency       string
	BaseCurrencyLocked int64
	CreatedAt          string
}

type TenantMembership struct {
	TenantID  string
	UserID    string
	Role      string
	CreatedAt string
}

type User struct {
	ID                 string
	Username           string
	UsernameNormalized string
	PasswordHash       string
	CreatedAt          string
	Locale             string
	Theme              string
	Accent             string
}
