// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

type Asset struct {
	ID          string
	TenantID    string
	VariantID   string
	DisplayName string
	CreatedAt   string
}

type ItemCategory struct {
	ID        string
	TenantID  string
	Name      string
	CreatedAt string
}

type ProductModel struct {
	ID         string
	TenantID   string
	CategoryID string
	Name       string
	CreatedAt  string
}

type ProductVariant struct {
	ID        string
	TenantID  string
	ModelID   string
	Name      string
	CreatedAt string
}

type Tenant struct {
	ID                 string
	Name               string
	BaseCurrency       string
	BaseCurrencyLocked int64
	CreatedAt          string
}
