// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :exec
INSERT INTO assets (id, tenant_id, variant_id, display_name, created_at) VALUES (?, ?, ?, ?, ?)
`

type CreateAssetParams struct {
	ID          string
	TenantID    string
	VariantID   string
	DisplayName string
	CreatedAt   string
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) error {
	_, err := q.db.ExecContext(ctx, createAsset,
		arg.ID,
		arg.TenantID,
		arg.VariantID,
		arg.DisplayName,
		arg.CreatedAt,
	)
	return err
}

const createCatalogAsset = `-- name: CreateCatalogAsset :exec
INSERT INTO assets
    (id, tenant_id, variant_id, display_name, serial_number, color, purchase_channel, notes, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCatalogAssetParams struct {
	ID              string
	TenantID        string
	VariantID       string
	DisplayName     string
	SerialNumber    string
	Color           string
	PurchaseChannel string
	Notes           string
	CreatedAt       string
}

func (q *Queries) CreateCatalogAsset(ctx context.Context, arg CreateCatalogAssetParams) error {
	_, err := q.db.ExecContext(ctx, createCatalogAsset,
		arg.ID,
		arg.TenantID,
		arg.VariantID,
		arg.DisplayName,
		arg.SerialNumber,
		arg.Color,
		arg.PurchaseChannel,
		arg.Notes,
		arg.CreatedAt,
	)
	return err
}

const createCategory = `-- name: CreateCategory :exec
INSERT INTO item_categories (id, tenant_id, name, created_at)
VALUES (?, ?, ?, ?)
`

type CreateCategoryParams struct {
	ID        string
	TenantID  string
	Name      string
	CreatedAt string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const createMembership = `-- name: CreateMembership :exec
INSERT INTO tenant_memberships (tenant_id, user_id, role, created_at)
VALUES (?, ?, ?, ?)
`

type CreateMembershipParams struct {
	TenantID  string
	UserID    string
	Role      string
	CreatedAt string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.ExecContext(ctx, createMembership,
		arg.TenantID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const createModel = `-- name: CreateModel :exec
INSERT INTO product_models (id, tenant_id, category_id, name, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateModelParams struct {
	ID         string
	TenantID   string
	CategoryID string
	Name       string
	CreatedAt  string
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) error {
	_, err := q.db.ExecContext(ctx, createModel,
		arg.ID,
		arg.TenantID,
		arg.CategoryID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const createSecurityAuditEvent = `-- name: CreateSecurityAuditEvent :exec
INSERT INTO security_audit_events
    (id, tenant_id, actor_user_id, action, target_user_id, detail, occurred_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSecurityAuditEventParams struct {
	ID           string
	TenantID     string
	ActorUserID  sql.NullString
	Action       string
	TargetUserID sql.NullString
	Detail       string
	OccurredAt   string
}

func (q *Queries) CreateSecurityAuditEvent(ctx context.Context, arg CreateSecurityAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, createSecurityAuditEvent,
		arg.ID,
		arg.TenantID,
		arg.ActorUserID,
		arg.Action,
		arg.TargetUserID,
		arg.Detail,
		arg.OccurredAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, tenant_id, user_id, expires_at, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	TokenHash string
	TenantID  string
	UserID    string
	ExpiresAt string
	CreatedAt string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.TenantID,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createTenant = `-- name: CreateTenant :exec
INSERT INTO tenants (id, name, base_currency, created_at) VALUES (?, ?, ?, ?)
`

type CreateTenantParams struct {
	ID           string
	Name         string
	BaseCurrency string
	CreatedAt    string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.ExecContext(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.BaseCurrency,
		arg.CreatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, username_normalized, password_hash, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID                 string
	Username           string
	UsernameNormalized string
	PasswordHash       string
	CreatedAt          string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.UsernameNormalized,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}

const createVariant = `-- name: CreateVariant :exec
INSERT INTO product_variants (id, tenant_id, model_id, name, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateVariantParams struct {
	ID        string
	TenantID  string
	ModelID   string
	Name      string
	CreatedAt string
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) error {
	_, err := q.db.ExecContext(ctx, createVariant,
		arg.ID,
		arg.TenantID,
		arg.ModelID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const ensureCategory = `-- name: EnsureCategory :one
INSERT INTO item_categories (id, tenant_id, name, created_at) VALUES (?, ?, ?, ?)
ON CONFLICT (tenant_id, name) DO UPDATE SET name = excluded.name
RETURNING id
`

type EnsureCategoryParams struct {
	ID        string
	TenantID  string
	Name      string
	CreatedAt string
}

func (q *Queries) EnsureCategory(ctx context.Context, arg EnsureCategoryParams) (string, error) {
	row := q.db.QueryRowContext(ctx, ensureCategory,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.CreatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const ensureModel = `-- name: EnsureModel :one
INSERT INTO product_models (id, tenant_id, category_id, name, created_at) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (tenant_id, category_id, name) DO UPDATE SET name = excluded.name
RETURNING id
`

type EnsureModelParams struct {
	ID         string
	TenantID   string
	CategoryID string
	Name       string
	CreatedAt  string
}

func (q *Queries) EnsureModel(ctx context.Context, arg EnsureModelParams) (string, error) {
	row := q.db.QueryRowContext(ctx, ensureModel,
		arg.ID,
		arg.TenantID,
		arg.CategoryID,
		arg.Name,
		arg.CreatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const ensureTenant = `-- name: EnsureTenant :exec
INSERT INTO tenants (id, name, base_currency, created_at) VALUES (?, ?, ?, ?)
ON CONFLICT (id) DO NOTHING
`

type EnsureTenantParams struct {
	ID           string
	Name         string
	BaseCurrency string
	CreatedAt    string
}

func (q *Queries) EnsureTenant(ctx context.Context, arg EnsureTenantParams) error {
	_, err := q.db.ExecContext(ctx, ensureTenant,
		arg.ID,
		arg.Name,
		arg.BaseCurrency,
		arg.CreatedAt,
	)
	return err
}

const ensureVariant = `-- name: EnsureVariant :one
INSERT INTO product_variants (id, tenant_id, model_id, name, created_at) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (tenant_id, model_id, name) DO UPDATE SET name = excluded.name
RETURNING id
`

type EnsureVariantParams struct {
	ID        string
	TenantID  string
	ModelID   string
	Name      string
	CreatedAt string
}

func (q *Queries) EnsureVariant(ctx context.Context, arg EnsureVariantParams) (string, error) {
	row := q.db.QueryRowContext(ctx, ensureVariant,
		arg.ID,
		arg.TenantID,
		arg.ModelID,
		arg.Name,
		arg.CreatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const findAccountByUsername = `-- name: FindAccountByUsername :one
SELECT u.id AS user_id, u.username, u.password_hash,
       tm.tenant_id, tm.role, t.name AS tenant_name
FROM users u
JOIN tenant_memberships tm ON tm.user_id = u.id
JOIN tenants t ON t.id = tm.tenant_id
WHERE u.username_normalized = ?
ORDER BY tm.created_at
LIMIT 1
`

type FindAccountByUsernameRow struct {
	UserID       string
	Username     string
	PasswordHash string
	TenantID     string
	Role         string
	TenantName   string
}

func (q *Queries) FindAccountByUsername(ctx context.Context, usernameNormalized string) (FindAccountByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, findAccountByUsername, usernameNormalized)
	var i FindAccountByUsernameRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.PasswordHash,
		&i.TenantID,
		&i.Role,
		&i.TenantName,
	)
	return i, err
}

const firstPrincipal = `-- name: FirstPrincipal :one
SELECT tm.tenant_id, u.id AS user_id, u.username, tm.role, t.name AS tenant_name
FROM users u
JOIN tenant_memberships tm ON tm.user_id = u.id
JOIN tenants t ON t.id = tm.tenant_id
ORDER BY u.created_at, tm.created_at
LIMIT 1
`

type FirstPrincipalRow struct {
	TenantID   string
	UserID     string
	Username   string
	Role       string
	TenantName string
}

func (q *Queries) FirstPrincipal(ctx context.Context) (FirstPrincipalRow, error) {
	row := q.db.QueryRowContext(ctx, firstPrincipal)
	var i FirstPrincipalRow
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.TenantName,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT a.id, a.tenant_id, c.id AS category_id, c.name AS category_name,
       m.id AS model_id, m.name AS model_name, v.id AS variant_id,
       v.name AS variant_name, a.display_name, a.serial_number, a.color,
       a.purchase_channel, a.notes, a.created_at
FROM assets a
JOIN product_variants v ON v.tenant_id = a.tenant_id AND v.id = a.variant_id
JOIN product_models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
WHERE a.tenant_id = ? AND a.id = ?
`

type GetAssetParams struct {
	TenantID string
	ID       string
}

type GetAssetRow struct {
	ID              string
	TenantID        string
	CategoryID      string
	CategoryName    string
	ModelID         string
	ModelName       string
	VariantID       string
	VariantName     string
	DisplayName     string
	SerialNumber    string
	Color           string
	PurchaseChannel string
	Notes           string
	CreatedAt       string
}

func (q *Queries) GetAsset(ctx context.Context, arg GetAssetParams) (GetAssetRow, error) {
	row := q.db.QueryRowContext(ctx, getAsset, arg.TenantID, arg.ID)
	var i GetAssetRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.CategoryName,
		&i.ModelID,
		&i.ModelName,
		&i.VariantID,
		&i.VariantName,
		&i.DisplayName,
		&i.SerialNumber,
		&i.Color,
		&i.PurchaseChannel,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionPrincipal = `-- name: GetSessionPrincipal :one
SELECT s.tenant_id, s.user_id, u.username, tm.role, t.name AS tenant_name
FROM sessions s
JOIN users u ON u.id = s.user_id
JOIN tenant_memberships tm ON tm.tenant_id = s.tenant_id AND tm.user_id = s.user_id
JOIN tenants t ON t.id = s.tenant_id
WHERE s.token_hash = ? AND s.expires_at > ?
`

type GetSessionPrincipalParams struct {
	TokenHash string
	ExpiresAt string
}

type GetSessionPrincipalRow struct {
	TenantID   string
	UserID     string
	Username   string
	Role       string
	TenantName string
}

func (q *Queries) GetSessionPrincipal(ctx context.Context, arg GetSessionPrincipalParams) (GetSessionPrincipalRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionPrincipal, arg.TokenHash, arg.ExpiresAt)
	var i GetSessionPrincipalRow
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.TenantName,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT a.id, a.tenant_id, c.id AS category_id, c.name AS category_name,
       m.id AS model_id, m.name AS model_name, v.id AS variant_id,
       v.name AS variant_name, a.display_name, a.serial_number, a.color,
       a.purchase_channel, a.notes, a.created_at
FROM assets a
JOIN product_variants v ON v.tenant_id = a.tenant_id AND v.id = a.variant_id
JOIN product_models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
WHERE a.tenant_id = ?
ORDER BY a.created_at DESC, a.id
`

type ListAssetsRow struct {
	ID              string
	TenantID        string
	CategoryID      string
	CategoryName    string
	ModelID         string
	ModelName       string
	VariantID       string
	VariantName     string
	DisplayName     string
	SerialNumber    string
	Color           string
	PurchaseChannel string
	Notes           string
	CreatedAt       string
}

func (q *Queries) ListAssets(ctx context.Context, tenantID string) ([]ListAssetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssets, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsRow
	for rows.Next() {
		var i ListAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.CategoryName,
			&i.ModelID,
			&i.ModelName,
			&i.VariantID,
			&i.VariantName,
			&i.DisplayName,
			&i.SerialNumber,
			&i.Color,
			&i.PurchaseChannel,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, tenant_id, name, created_at
FROM item_categories
WHERE tenant_id = ?
ORDER BY name, id
`

func (q *Queries) ListCategories(ctx context.Context, tenantID string) ([]ItemCategory, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemCategory
	for rows.Next() {
		var i ItemCategory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT u.id AS user_id, u.username, tm.role, tm.created_at
FROM tenant_memberships tm
JOIN users u ON u.id = tm.user_id
WHERE tm.tenant_id = ?
ORDER BY u.username_normalized
`

type ListMembersRow struct {
	UserID    string
	Username  string
	Role      string
	CreatedAt string
}

func (q *Queries) ListMembers(ctx context.Context, tenantID string) ([]ListMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many
SELECT m.id, m.tenant_id, m.category_id, c.name AS category_name, m.name, m.created_at
FROM product_models m
JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
WHERE m.tenant_id = ?
ORDER BY c.name, m.name, m.id
`

type ListModelsRow struct {
	ID           string
	TenantID     string
	CategoryID   string
	CategoryName string
	Name         string
	CreatedAt    string
}

func (q *Queries) ListModels(ctx context.Context, tenantID string) ([]ListModelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listModels, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelsRow
	for rows.Next() {
		var i ListModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.CategoryName,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariants = `-- name: ListVariants :many
SELECT v.id, v.tenant_id, m.category_id, c.name AS category_name,
       v.model_id, m.name AS model_name, v.name, v.created_at
FROM product_variants v
JOIN product_models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
WHERE v.tenant_id = ?
ORDER BY c.name, m.name, v.name, v.id
`

type ListVariantsRow struct {
	ID           string
	TenantID     string
	CategoryID   string
	CategoryName string
	ModelID      string
	ModelName    string
	Name         string
	CreatedAt    string
}

func (q *Queries) ListVariants(ctx context.Context, tenantID string) ([]ListVariantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVariants, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVariantsRow
	for rows.Next() {
		var i ListVariantsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.CategoryName,
			&i.ModelID,
			&i.ModelName,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
