// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const countAssetsWithSummary = `-- name: CountAssetsWithSummary :one
WITH effective_events AS (
SELECT e.id, e.tenant_id, e.asset_id, e.transaction_id, e.event_type, e.base_amount_minor, e.base_currency, e.original_amount_minor, e.original_currency, e.fx_rate_scaled, e.fx_rate_date, e.fx_rate_source, e.notes, e.voids_event_id, e.replaces_event_id, e.occurred_at, e.created_by_user_id, e.created_at
FROM asset_events e
WHERE e.tenant_id = ?2
  AND e.event_type != 'void'
  AND NOT EXISTS (
      SELECT 1 FROM asset_events void_event
      WHERE void_event.tenant_id = e.tenant_id AND void_event.voids_event_id = e.id
  )
),
event_rollup AS (
SELECT asset_id,
       MAX(CASE WHEN event_type = 'purchase' THEN 1 ELSE 0 END) AS has_purchase,
       MAX(CASE WHEN event_type = 'sale' THEN 1 ELSE 0 END) AS has_sale
FROM effective_events
GROUP BY asset_id
),
ranked_events AS (
SELECT asset_id, event_type,
       ROW_NUMBER() OVER (PARTITION BY asset_id ORDER BY occurred_at DESC, created_at DESC, id DESC) AS event_rank
FROM effective_events
WHERE event_type IN ('purchase', 'repair', 'sale')
),
asset_rows AS (
SELECT a.id,
       COALESCE(er.has_purchase, 0) AS has_purchase,
       COALESCE(er.has_sale, 0) AS has_sale,
       COALESCE(re.event_type, '') AS latest_event_type
FROM assets a
JOIN product_variants v ON v.tenant_id = a.tenant_id AND v.id = a.variant_id
JOIN product_models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
LEFT JOIN event_rollup er ON er.asset_id = a.id
LEFT JOIN ranked_events re ON re.asset_id = a.id AND re.event_rank = 1
WHERE a.tenant_id = ?2
  AND (CAST(?3 AS TEXT) = '' OR (
       LOWER(a.display_name) LIKE '%' || LOWER(CAST(?3 AS TEXT)) || '%' OR
       LOWER(a.serial_number) LIKE '%' || LOWER(CAST(?3 AS TEXT)) || '%' OR
       LOWER(a.color) LIKE '%' || LOWER(CAST(?3 AS TEXT)) || '%' OR
       LOWER(a.purchase_channel) LIKE '%' || LOWER(CAST(?3 AS TEXT)) || '%' OR
       LOWER(a.notes) LIKE '%' || LOWER(CAST(?3 AS TEXT)) || '%' OR
       LOWER(m.name) LIKE '%' || LOWER(CAST(?3 AS TEXT)) || '%' OR
       LOWER(v.name) LIKE '%' || LOWER(CAST(?3 AS TEXT)) || '%' OR
       LOWER(c.name) LIKE '%' || LOWER(CAST(?3 AS TEXT)) || '%'
  ))
)
SELECT COUNT(*) FROM asset_rows
WHERE CAST(?1 AS TEXT) = '' OR CAST(?1 AS TEXT) = 'all'
   OR (CAST(?1 AS TEXT) = 'sold' AND has_sale = 1)
   OR (CAST(?1 AS TEXT) = 'repairing' AND has_sale = 0 AND has_purchase = 1 AND latest_event_type = 'repair')
   OR (CAST(?1 AS TEXT) = 'active' AND has_sale = 0 AND has_purchase = 1 AND latest_event_type != 'repair')
   OR (CAST(?1 AS TEXT) = 'unacquired' AND has_sale = 0 AND has_purchase = 0)
`

type CountAssetsWithSummaryParams struct {
	StatusFilter string
	TenantID     string
	SearchQuery  string
}

func (q *Queries) CountAssetsWithSummary(ctx context.Context, arg CountAssetsWithSummaryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAssetsWithSummary, arg.StatusFilter, arg.TenantID, arg.SearchQuery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :exec
INSERT INTO assets (id, tenant_id, variant_id, display_name, created_at) VALUES (?, ?, ?, ?, ?)
`

type CreateAssetParams struct {
	ID          string
	TenantID    string
	VariantID   string
	DisplayName string
	CreatedAt   string
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) error {
	_, err := q.db.ExecContext(ctx, createAsset,
		arg.ID,
		arg.TenantID,
		arg.VariantID,
		arg.DisplayName,
		arg.CreatedAt,
	)
	return err
}

const createAssetEvent = `-- name: CreateAssetEvent :exec
INSERT INTO asset_events
    (id, tenant_id, asset_id, transaction_id, event_type, base_amount_minor,
     base_currency, original_amount_minor, original_currency, fx_rate_scaled,
     fx_rate_date, fx_rate_source, notes, voids_event_id, replaces_event_id,
     occurred_at, created_by_user_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAssetEventParams struct {
	ID                  string
	TenantID            string
	AssetID             string
	TransactionID       string
	EventType           string
	BaseAmountMinor     int64
	BaseCurrency        string
	OriginalAmountMinor sql.NullInt64
	OriginalCurrency    sql.NullString
	FxRateScaled        sql.NullInt64
	FxRateDate          sql.NullString
	FxRateSource        sql.NullString
	Notes               string
	VoidsEventID        sql.NullString
	ReplacesEventID     sql.NullString
	OccurredAt          string
	CreatedByUserID     string
	CreatedAt           string
}

func (q *Queries) CreateAssetEvent(ctx context.Context, arg CreateAssetEventParams) error {
	_, err := q.db.ExecContext(ctx, createAssetEvent,
		arg.ID,
		arg.TenantID,
		arg.AssetID,
		arg.TransactionID,
		arg.EventType,
		arg.BaseAmountMinor,
		arg.BaseCurrency,
		arg.OriginalAmountMinor,
		arg.OriginalCurrency,
		arg.FxRateScaled,
		arg.FxRateDate,
		arg.FxRateSource,
		arg.Notes,
		arg.VoidsEventID,
		arg.ReplacesEventID,
		arg.OccurredAt,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	return err
}

const createAssetEventType = `-- name: CreateAssetEventType :exec
INSERT INTO asset_event_types
    (id, tenant_id, name, normalized_name, cashflow_direction, created_by_user_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAssetEventTypeParams struct {
	ID                string
	TenantID          string
	Name              string
	NormalizedName    string
	CashflowDirection string
	CreatedByUserID   string
	CreatedAt         string
}

func (q *Queries) CreateAssetEventType(ctx context.Context, arg CreateAssetEventTypeParams) error {
	_, err := q.db.ExecContext(ctx, createAssetEventType,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.NormalizedName,
		arg.CashflowDirection,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	return err
}

const createAssetTransaction = `-- name: CreateAssetTransaction :exec
INSERT INTO asset_transactions
    (id, tenant_id, occurred_at, source, external_reference, notes, created_by_user_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAssetTransactionParams struct {
	ID                string
	TenantID          string
	OccurredAt        string
	Source            string
	ExternalReference string
	Notes             string
	CreatedByUserID   string
	CreatedAt         string
}

func (q *Queries) CreateAssetTransaction(ctx context.Context, arg CreateAssetTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createAssetTransaction,
		arg.ID,
		arg.TenantID,
		arg.OccurredAt,
		arg.Source,
		arg.ExternalReference,
		arg.Notes,
		arg.CreatedByUserID,
		arg.CreatedAt,
	)
	return err
}

const createCatalogAsset = `-- name: CreateCatalogAsset :exec
INSERT INTO assets
    (id, tenant_id, variant_id, display_name, serial_number, color, purchase_channel, notes, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCatalogAssetParams struct {
	ID              string
	TenantID        string
	VariantID       string
	DisplayName     string
	SerialNumber    string
	Color           string
	PurchaseChannel string
	Notes           string
	CreatedAt       string
}

func (q *Queries) CreateCatalogAsset(ctx context.Context, arg CreateCatalogAssetParams) error {
	_, err := q.db.ExecContext(ctx, createCatalogAsset,
		arg.ID,
		arg.TenantID,
		arg.VariantID,
		arg.DisplayName,
		arg.SerialNumber,
		arg.Color,
		arg.PurchaseChannel,
		arg.Notes,
		arg.CreatedAt,
	)
	return err
}

const createCategory = `-- name: CreateCategory :exec
INSERT INTO item_categories (id, tenant_id, name, icon_key, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateCategoryParams struct {
	ID        string
	TenantID  string
	Name      string
	IconKey   string
	CreatedAt string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.IconKey,
		arg.CreatedAt,
	)
	return err
}

const createMembership = `-- name: CreateMembership :exec
INSERT INTO tenant_memberships (tenant_id, user_id, role, created_at)
VALUES (?, ?, ?, ?)
`

type CreateMembershipParams struct {
	TenantID  string
	UserID    string
	Role      string
	CreatedAt string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.ExecContext(ctx, createMembership,
		arg.TenantID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const createModel = `-- name: CreateModel :exec
INSERT INTO product_models (id, tenant_id, category_id, name, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateModelParams struct {
	ID         string
	TenantID   string
	CategoryID string
	Name       string
	CreatedAt  string
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) error {
	_, err := q.db.ExecContext(ctx, createModel,
		arg.ID,
		arg.TenantID,
		arg.CategoryID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const createSecurityAuditEvent = `-- name: CreateSecurityAuditEvent :exec
INSERT INTO security_audit_events
    (id, tenant_id, actor_user_id, action, target_user_id, detail, occurred_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSecurityAuditEventParams struct {
	ID           string
	TenantID     string
	ActorUserID  sql.NullString
	Action       string
	TargetUserID sql.NullString
	Detail       string
	OccurredAt   string
}

func (q *Queries) CreateSecurityAuditEvent(ctx context.Context, arg CreateSecurityAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, createSecurityAuditEvent,
		arg.ID,
		arg.TenantID,
		arg.ActorUserID,
		arg.Action,
		arg.TargetUserID,
		arg.Detail,
		arg.OccurredAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, tenant_id, user_id, expires_at, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	TokenHash string
	TenantID  string
	UserID    string
	ExpiresAt string
	CreatedAt string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.TenantID,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createTenant = `-- name: CreateTenant :exec
INSERT INTO tenants (id, name, base_currency, created_at) VALUES (?, ?, ?, ?)
`

type CreateTenantParams struct {
	ID           string
	Name         string
	BaseCurrency string
	CreatedAt    string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.ExecContext(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.BaseCurrency,
		arg.CreatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, username_normalized, password_hash, locale, theme, accent, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID                 string
	Username           string
	UsernameNormalized string
	PasswordHash       string
	Locale             string
	Theme              string
	Accent             string
	CreatedAt          string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.UsernameNormalized,
		arg.PasswordHash,
		arg.Locale,
		arg.Theme,
		arg.Accent,
		arg.CreatedAt,
	)
	return err
}

const createVariant = `-- name: CreateVariant :exec
INSERT INTO product_variants (id, tenant_id, model_id, name, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateVariantParams struct {
	ID        string
	TenantID  string
	ModelID   string
	Name      string
	CreatedAt string
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) error {
	_, err := q.db.ExecContext(ctx, createVariant,
		arg.ID,
		arg.TenantID,
		arg.ModelID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const deleteVariant = `-- name: DeleteVariant :execrows
DELETE FROM product_variants AS variant
WHERE variant.tenant_id = ? AND variant.id = ?
  AND NOT EXISTS (
    SELECT 1 FROM assets
    WHERE assets.tenant_id = variant.tenant_id
      AND assets.variant_id = variant.id
  )
`

type DeleteVariantParams struct {
	TenantID string
	ID       string
}

func (q *Queries) DeleteVariant(ctx context.Context, arg DeleteVariantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteVariant, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensureCategory = `-- name: EnsureCategory :one
INSERT INTO item_categories (id, tenant_id, name, created_at) VALUES (?, ?, ?, ?)
ON CONFLICT (tenant_id, name) DO UPDATE SET name = excluded.name
RETURNING id
`

type EnsureCategoryParams struct {
	ID        string
	TenantID  string
	Name      string
	CreatedAt string
}

func (q *Queries) EnsureCategory(ctx context.Context, arg EnsureCategoryParams) (string, error) {
	row := q.db.QueryRowContext(ctx, ensureCategory,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.CreatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const ensureModel = `-- name: EnsureModel :one
INSERT INTO product_models (id, tenant_id, category_id, name, created_at) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (tenant_id, category_id, name) DO UPDATE SET name = excluded.name
RETURNING id
`

type EnsureModelParams struct {
	ID         string
	TenantID   string
	CategoryID string
	Name       string
	CreatedAt  string
}

func (q *Queries) EnsureModel(ctx context.Context, arg EnsureModelParams) (string, error) {
	row := q.db.QueryRowContext(ctx, ensureModel,
		arg.ID,
		arg.TenantID,
		arg.CategoryID,
		arg.Name,
		arg.CreatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const ensureTenant = `-- name: EnsureTenant :exec
INSERT INTO tenants (id, name, base_currency, created_at) VALUES (?, ?, ?, ?)
ON CONFLICT (id) DO NOTHING
`

type EnsureTenantParams struct {
	ID           string
	Name         string
	BaseCurrency string
	CreatedAt    string
}

func (q *Queries) EnsureTenant(ctx context.Context, arg EnsureTenantParams) error {
	_, err := q.db.ExecContext(ctx, ensureTenant,
		arg.ID,
		arg.Name,
		arg.BaseCurrency,
		arg.CreatedAt,
	)
	return err
}

const ensureVariant = `-- name: EnsureVariant :one
INSERT INTO product_variants (id, tenant_id, model_id, name, created_at) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (tenant_id, model_id, name) DO UPDATE SET name = excluded.name
RETURNING id
`

type EnsureVariantParams struct {
	ID        string
	TenantID  string
	ModelID   string
	Name      string
	CreatedAt string
}

func (q *Queries) EnsureVariant(ctx context.Context, arg EnsureVariantParams) (string, error) {
	row := q.db.QueryRowContext(ctx, ensureVariant,
		arg.ID,
		arg.TenantID,
		arg.ModelID,
		arg.Name,
		arg.CreatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const findAccountByUsername = `-- name: FindAccountByUsername :one
SELECT u.id AS user_id, u.username, u.password_hash, u.locale, u.theme, u.accent,
       tm.tenant_id, tm.role, t.name AS tenant_name
FROM users u
JOIN tenant_memberships tm ON tm.user_id = u.id
JOIN tenants t ON t.id = tm.tenant_id
WHERE u.username_normalized = ?
ORDER BY tm.created_at
LIMIT 1
`

type FindAccountByUsernameRow struct {
	UserID       string
	Username     string
	PasswordHash string
	Locale       string
	Theme        string
	Accent       string
	TenantID     string
	Role         string
	TenantName   string
}

func (q *Queries) FindAccountByUsername(ctx context.Context, usernameNormalized string) (FindAccountByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, findAccountByUsername, usernameNormalized)
	var i FindAccountByUsernameRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.PasswordHash,
		&i.Locale,
		&i.Theme,
		&i.Accent,
		&i.TenantID,
		&i.Role,
		&i.TenantName,
	)
	return i, err
}

const findLifecycleRequest = `-- name: FindLifecycleRequest :one
SELECT request_hash, event_id FROM lifecycle_requests
WHERE tenant_id = ?1 AND user_id = ?2 AND request_key = ?3
`

type FindLifecycleRequestParams struct {
	TenantID   string
	UserID     string
	RequestKey string
}

type FindLifecycleRequestRow struct {
	RequestHash string
	EventID     string
}

func (q *Queries) FindLifecycleRequest(ctx context.Context, arg FindLifecycleRequestParams) (FindLifecycleRequestRow, error) {
	row := q.db.QueryRowContext(ctx, findLifecycleRequest, arg.TenantID, arg.UserID, arg.RequestKey)
	var i FindLifecycleRequestRow
	err := row.Scan(&i.RequestHash, &i.EventID)
	return i, err
}

const firstPrincipal = `-- name: FirstPrincipal :one
SELECT tm.tenant_id, u.id AS user_id, u.username, tm.role, t.name AS tenant_name,
       u.locale, u.theme, u.accent
FROM users u
JOIN tenant_memberships tm ON tm.user_id = u.id
JOIN tenants t ON t.id = tm.tenant_id
ORDER BY u.created_at, tm.created_at
LIMIT 1
`

type FirstPrincipalRow struct {
	TenantID   string
	UserID     string
	Username   string
	Role       string
	TenantName string
	Locale     string
	Theme      string
	Accent     string
}

func (q *Queries) FirstPrincipal(ctx context.Context) (FirstPrincipalRow, error) {
	row := q.db.QueryRowContext(ctx, firstPrincipal)
	var i FirstPrincipalRow
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.TenantName,
		&i.Locale,
		&i.Theme,
		&i.Accent,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT a.id, a.tenant_id, c.id AS category_id, c.name AS category_name,
       c.icon_key AS category_icon,
       m.id AS model_id, m.name AS model_name, v.id AS variant_id,
       v.name AS variant_name, a.display_name, a.serial_number, a.color,
       a.purchase_channel, a.notes, a.created_at
FROM assets a
JOIN product_variants v ON v.tenant_id = a.tenant_id AND v.id = a.variant_id
JOIN product_models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
WHERE a.tenant_id = ? AND a.id = ?
`

type GetAssetParams struct {
	TenantID string
	ID       string
}

type GetAssetRow struct {
	ID              string
	TenantID        string
	CategoryID      string
	CategoryName    string
	CategoryIcon    string
	ModelID         string
	ModelName       string
	VariantID       string
	VariantName     string
	DisplayName     string
	SerialNumber    string
	Color           string
	PurchaseChannel string
	Notes           string
	CreatedAt       string
}

func (q *Queries) GetAsset(ctx context.Context, arg GetAssetParams) (GetAssetRow, error) {
	row := q.db.QueryRowContext(ctx, getAsset, arg.TenantID, arg.ID)
	var i GetAssetRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategoryIcon,
		&i.ModelID,
		&i.ModelName,
		&i.VariantID,
		&i.VariantName,
		&i.DisplayName,
		&i.SerialNumber,
		&i.Color,
		&i.PurchaseChannel,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetEvent = `-- name: GetAssetEvent :one
SELECT e.id, e.tenant_id, e.asset_id, e.transaction_id, e.event_type,
       e.base_amount_minor, e.base_currency, e.original_amount_minor,
       e.original_currency, e.fx_rate_scaled, e.fx_rate_date, e.fx_rate_source,
       e.notes, e.voids_event_id, e.replaces_event_id, e.occurred_at,
       e.created_by_user_id, e.created_at,
       EXISTS (
           SELECT 1 FROM asset_events v
           WHERE v.tenant_id = e.tenant_id AND v.voids_event_id = e.id
       ) AS is_voided
FROM asset_events e
WHERE e.tenant_id = ? AND e.id = ?
`

type GetAssetEventParams struct {
	TenantID string
	ID       string
}

type GetAssetEventRow struct {
	ID                  string
	TenantID            string
	AssetID             string
	TransactionID       string
	EventType           string
	BaseAmountMinor     int64
	BaseCurrency        string
	OriginalAmountMinor sql.NullInt64
	OriginalCurrency    sql.NullString
	FxRateScaled        sql.NullInt64
	FxRateDate          sql.NullString
	FxRateSource        sql.NullString
	Notes               string
	VoidsEventID        sql.NullString
	ReplacesEventID     sql.NullString
	OccurredAt          string
	CreatedByUserID     string
	CreatedAt           string
	IsVoided            bool
}

func (q *Queries) GetAssetEvent(ctx context.Context, arg GetAssetEventParams) (GetAssetEventRow, error) {
	row := q.db.QueryRowContext(ctx, getAssetEvent, arg.TenantID, arg.ID)
	var i GetAssetEventRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetID,
		&i.TransactionID,
		&i.EventType,
		&i.BaseAmountMinor,
		&i.BaseCurrency,
		&i.OriginalAmountMinor,
		&i.OriginalCurrency,
		&i.FxRateScaled,
		&i.FxRateDate,
		&i.FxRateSource,
		&i.Notes,
		&i.VoidsEventID,
		&i.ReplacesEventID,
		&i.OccurredAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.IsVoided,
	)
	return i, err
}

const getAssetSummary = `-- name: GetAssetSummary :one
WITH effective_events AS (
    SELECT e.id, e.tenant_id, e.asset_id, e.transaction_id, e.event_type, e.base_amount_minor, e.base_currency, e.original_amount_minor, e.original_currency, e.fx_rate_scaled, e.fx_rate_date, e.fx_rate_source, e.notes, e.voids_event_id, e.replaces_event_id, e.occurred_at, e.created_by_user_id, e.created_at
    FROM asset_events e
    WHERE e.tenant_id = ?2 AND e.asset_id = ?1
      AND e.event_type != 'void'
      AND NOT EXISTS (SELECT 1 FROM asset_events v WHERE v.tenant_id = e.tenant_id AND v.voids_event_id = e.id)
), latest_event AS (
    SELECT event_type FROM effective_events
    WHERE event_type IN ('purchase', 'repair', 'sale')
    ORDER BY occurred_at DESC, created_at DESC, id DESC LIMIT 1
)
SELECT t.base_currency,
       CAST(COALESCE(SUM(CASE WHEN e.base_amount_minor < 0 THEN -e.base_amount_minor ELSE 0 END), 0) AS INTEGER) AS expense_minor,
       CAST(COALESCE(SUM(CASE WHEN e.base_amount_minor > 0 THEN e.base_amount_minor ELSE 0 END), 0) AS INTEGER) AS income_minor,
       CAST(COALESCE(SUM(e.base_amount_minor), 0) AS INTEGER) AS net_minor,
       CASE
         WHEN COALESCE(MAX(CASE WHEN e.event_type = 'sale' THEN 1 ELSE 0 END), 0) = 1 THEN 'sold'
         WHEN COALESCE(MAX(CASE WHEN e.event_type = 'purchase' THEN 1 ELSE 0 END), 0) = 0 THEN 'unacquired'
         WHEN COALESCE((SELECT event_type FROM latest_event), '') = 'repair' THEN 'repairing'
         ELSE 'active'
       END AS status
FROM tenants t
JOIN assets a ON a.tenant_id = t.id AND a.id = ?1
LEFT JOIN effective_events e ON e.asset_id = a.id
WHERE t.id = ?2
GROUP BY t.base_currency
`

type GetAssetSummaryParams struct {
	AssetID  string
	TenantID string
}

type GetAssetSummaryRow struct {
	BaseCurrency string
	ExpenseMinor int64
	IncomeMinor  int64
	NetMinor     int64
	Status       string
}

func (q *Queries) GetAssetSummary(ctx context.Context, arg GetAssetSummaryParams) (GetAssetSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getAssetSummary, arg.AssetID, arg.TenantID)
	var i GetAssetSummaryRow
	err := row.Scan(
		&i.BaseCurrency,
		&i.ExpenseMinor,
		&i.IncomeMinor,
		&i.NetMinor,
		&i.Status,
	)
	return i, err
}

const getPortfolioSummary = `-- name: GetPortfolioSummary :one
WITH effective_events AS (
    SELECT e.id, e.tenant_id, e.asset_id, e.transaction_id, e.event_type, e.base_amount_minor, e.base_currency, e.original_amount_minor, e.original_currency, e.fx_rate_scaled, e.fx_rate_date, e.fx_rate_source, e.notes, e.voids_event_id, e.replaces_event_id, e.occurred_at, e.created_by_user_id, e.created_at
    FROM asset_events e
    WHERE e.tenant_id = ?1
      AND e.event_type != 'void'
      AND NOT EXISTS (
          SELECT 1 FROM asset_events void_event
          WHERE void_event.tenant_id = e.tenant_id AND void_event.voids_event_id = e.id
      )
)
SELECT COUNT(DISTINCT a.id) AS asset_count,
       CAST(COALESCE(SUM(CASE WHEN e.base_amount_minor < 0 THEN -e.base_amount_minor ELSE 0 END), 0) AS INTEGER) AS expense_minor,
       CAST(COALESCE(SUM(CASE WHEN e.base_amount_minor > 0 THEN e.base_amount_minor ELSE 0 END), 0) AS INTEGER) AS income_minor,
       CAST(COALESCE(SUM(e.base_amount_minor), 0) AS INTEGER) AS net_minor,
       t.base_currency
FROM tenants t
LEFT JOIN assets a ON a.tenant_id = t.id
LEFT JOIN effective_events e ON e.asset_id = a.id
WHERE t.id = ?1
GROUP BY t.base_currency
`

type GetPortfolioSummaryRow struct {
	AssetCount   int64
	ExpenseMinor int64
	IncomeMinor  int64
	NetMinor     int64
	BaseCurrency string
}

func (q *Queries) GetPortfolioSummary(ctx context.Context, tenantID string) (GetPortfolioSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getPortfolioSummary, tenantID)
	var i GetPortfolioSummaryRow
	err := row.Scan(
		&i.AssetCount,
		&i.ExpenseMinor,
		&i.IncomeMinor,
		&i.NetMinor,
		&i.BaseCurrency,
	)
	return i, err
}

const getProductModel = `-- name: GetProductModel :one
SELECT m.id, m.tenant_id, m.category_id, c.name AS category_name, c.icon_key AS category_icon, m.name, m.created_at,
       m.model_3d_store_id, m.model_3d_object_key, m.model_3d_sha256, m.model_3d_size_bytes,
       m.model_3d_source_url, m.model_3d_author, m.model_3d_license, m.model_3d_updated_at
FROM product_models m
JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
WHERE m.tenant_id = ? AND m.id = ?
`

type GetProductModelParams struct {
	TenantID string
	ID       string
}

type GetProductModelRow struct {
	ID               string
	TenantID         string
	CategoryID       string
	CategoryName     string
	CategoryIcon     string
	Name             string
	CreatedAt        string
	Model3dStoreID   sql.NullString
	Model3dObjectKey sql.NullString
	Model3dSha256    sql.NullString
	Model3dSizeBytes sql.NullInt64
	Model3dSourceUrl sql.NullString
	Model3dAuthor    sql.NullString
	Model3dLicense   sql.NullString
	Model3dUpdatedAt sql.NullString
}

func (q *Queries) GetProductModel(ctx context.Context, arg GetProductModelParams) (GetProductModelRow, error) {
	row := q.db.QueryRowContext(ctx, getProductModel, arg.TenantID, arg.ID)
	var i GetProductModelRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategoryIcon,
		&i.Name,
		&i.CreatedAt,
		&i.Model3dStoreID,
		&i.Model3dObjectKey,
		&i.Model3dSha256,
		&i.Model3dSizeBytes,
		&i.Model3dSourceUrl,
		&i.Model3dAuthor,
		&i.Model3dLicense,
		&i.Model3dUpdatedAt,
	)
	return i, err
}

const getSessionPrincipal = `-- name: GetSessionPrincipal :one
SELECT s.tenant_id, s.user_id, u.username, tm.role, t.name AS tenant_name,
       u.locale, u.theme, u.accent
FROM sessions s
JOIN users u ON u.id = s.user_id
JOIN tenant_memberships tm ON tm.tenant_id = s.tenant_id AND tm.user_id = s.user_id
JOIN tenants t ON t.id = s.tenant_id
WHERE s.token_hash = ? AND s.expires_at > ?
`

type GetSessionPrincipalParams struct {
	TokenHash string
	ExpiresAt string
}

type GetSessionPrincipalRow struct {
	TenantID   string
	UserID     string
	Username   string
	Role       string
	TenantName string
	Locale     string
	Theme      string
	Accent     string
}

func (q *Queries) GetSessionPrincipal(ctx context.Context, arg GetSessionPrincipalParams) (GetSessionPrincipalRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionPrincipal, arg.TokenHash, arg.ExpiresAt)
	var i GetSessionPrincipalRow
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.TenantName,
		&i.Locale,
		&i.Theme,
		&i.Accent,
	)
	return i, err
}

const getTenantBaseCurrency = `-- name: GetTenantBaseCurrency :one
SELECT base_currency, base_currency_locked
FROM tenants
WHERE id = ?
`

type GetTenantBaseCurrencyRow struct {
	BaseCurrency       string
	BaseCurrencyLocked int64
}

func (q *Queries) GetTenantBaseCurrency(ctx context.Context, id string) (GetTenantBaseCurrencyRow, error) {
	row := q.db.QueryRowContext(ctx, getTenantBaseCurrency, id)
	var i GetTenantBaseCurrencyRow
	err := row.Scan(&i.BaseCurrency, &i.BaseCurrencyLocked)
	return i, err
}

const listAssetEventTypes = `-- name: ListAssetEventTypes :many
SELECT id, tenant_id, name, normalized_name, cashflow_direction, created_by_user_id, created_at
FROM asset_event_types
WHERE tenant_id = ?
ORDER BY normalized_name, id
`

func (q *Queries) ListAssetEventTypes(ctx context.Context, tenantID string) ([]AssetEventType, error) {
	rows, err := q.db.QueryContext(ctx, listAssetEventTypes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetEventType
	for rows.Next() {
		var i AssetEventType
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.NormalizedName,
			&i.CashflowDirection,
			&i.CreatedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetEvents = `-- name: ListAssetEvents :many
SELECT e.id, e.tenant_id, e.asset_id, e.transaction_id, e.event_type,
       e.base_amount_minor, e.base_currency, e.original_amount_minor,
       e.original_currency, e.fx_rate_scaled, e.fx_rate_date, e.fx_rate_source,
       e.notes, e.voids_event_id, e.replaces_event_id, e.occurred_at,
       e.created_by_user_id, e.created_at,
       EXISTS (
           SELECT 1 FROM asset_events v
           WHERE v.tenant_id = e.tenant_id AND v.voids_event_id = e.id
       ) AS is_voided
FROM asset_events e
WHERE e.tenant_id = ? AND e.asset_id = ?
ORDER BY e.occurred_at, e.created_at, e.id
`

type ListAssetEventsParams struct {
	TenantID string
	AssetID  string
}

type ListAssetEventsRow struct {
	ID                  string
	TenantID            string
	AssetID             string
	TransactionID       string
	EventType           string
	BaseAmountMinor     int64
	BaseCurrency        string
	OriginalAmountMinor sql.NullInt64
	OriginalCurrency    sql.NullString
	FxRateScaled        sql.NullInt64
	FxRateDate          sql.NullString
	FxRateSource        sql.NullString
	Notes               string
	VoidsEventID        sql.NullString
	ReplacesEventID     sql.NullString
	OccurredAt          string
	CreatedByUserID     string
	CreatedAt           string
	IsVoided            bool
}

func (q *Queries) ListAssetEvents(ctx context.Context, arg ListAssetEventsParams) ([]ListAssetEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetEvents, arg.TenantID, arg.AssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetEventsRow
	for rows.Next() {
		var i ListAssetEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssetID,
			&i.TransactionID,
			&i.EventType,
			&i.BaseAmountMinor,
			&i.BaseCurrency,
			&i.OriginalAmountMinor,
			&i.OriginalCurrency,
			&i.FxRateScaled,
			&i.FxRateDate,
			&i.FxRateSource,
			&i.Notes,
			&i.VoidsEventID,
			&i.ReplacesEventID,
			&i.OccurredAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.IsVoided,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetEventsPage = `-- name: ListAssetEventsPage :many
WITH RECURSIVE list_options AS (
    SELECT CAST(?7 AS TEXT) AS sort_key,
           CAST(?8 AS TEXT) AS sort_direction,
           CAST(?9 AS INTEGER) AS show_voided
), event_lineage (id, root_created_at) AS (
    SELECT id, created_at
    FROM asset_events
    WHERE tenant_id = ?1 AND asset_id = ?2 AND replaces_event_id IS NULL
    UNION ALL
    SELECT e.id, lineage.root_created_at
    FROM asset_events e
    JOIN event_lineage lineage ON lineage.id = e.replaces_event_id
    WHERE e.tenant_id = ?1 AND e.asset_id = ?2
)
SELECT e.id, e.tenant_id, e.asset_id, e.transaction_id, e.event_type,
       e.base_amount_minor, e.base_currency, e.original_amount_minor,
       e.original_currency, e.fx_rate_scaled, e.fx_rate_date, e.fx_rate_source,
       e.notes, e.voids_event_id, e.replaces_event_id, e.occurred_at,
       e.created_by_user_id, e.created_at,
       EXISTS (
           SELECT 1 FROM asset_events v
           WHERE v.tenant_id = e.tenant_id AND v.voids_event_id = e.id
       ) AS is_voided,
       COUNT(*) OVER () AS total_count
FROM asset_events e
JOIN event_lineage lineage ON lineage.id = e.id
CROSS JOIN list_options o
WHERE e.tenant_id = ?1 AND e.asset_id = ?2
  AND e.event_type != 'void'
  AND (o.show_voided = 1 OR NOT EXISTS (
      SELECT 1 FROM asset_events v
      WHERE v.tenant_id = e.tenant_id AND v.voids_event_id = e.id
  ))
  AND (CAST(?3 AS TEXT) = '' OR LOWER(e.notes) LIKE '%' || LOWER(CAST(?3 AS TEXT)) || '%' OR LOWER(COALESCE(e.fx_rate_source, '')) LIKE '%' || LOWER(CAST(?3 AS TEXT)) || '%')
  AND (CAST(?4 AS TEXT) = '' OR e.event_type = CAST(?4 AS TEXT))
ORDER BY
  CASE WHEN o.sort_key = 'occurred' AND o.sort_direction = 'asc' THEN e.occurred_at END ASC,
  CASE WHEN o.sort_key = 'occurred' AND o.sort_direction = 'desc' THEN e.occurred_at END DESC,
  CASE WHEN o.sort_key = 'occurred' AND o.sort_direction = 'asc' THEN lineage.root_created_at END ASC,
  CASE WHEN o.sort_key = 'occurred' AND o.sort_direction = 'desc' THEN lineage.root_created_at END DESC,
  CASE WHEN o.sort_key = 'occurred' AND o.sort_direction = 'asc' THEN e.created_at END ASC,
  CASE WHEN o.sort_key = 'occurred' AND o.sort_direction = 'desc' THEN e.created_at END DESC,
  CASE WHEN o.sort_key = 'amount' AND o.sort_direction = 'asc' THEN e.base_amount_minor END ASC,
  CASE WHEN o.sort_key = 'amount' AND o.sort_direction = 'desc' THEN e.base_amount_minor END DESC,
  CASE WHEN o.sort_key = 'type' AND o.sort_direction = 'asc' THEN e.event_type END ASC,
  CASE WHEN o.sort_key = 'type' AND o.sort_direction = 'desc' THEN e.event_type END DESC,
  e.created_at DESC, e.id DESC
LIMIT ?6 OFFSET ?5
`

type ListAssetEventsPageParams struct {
	TenantID        string
	AssetID         string
	SearchQuery     string
	EventTypeFilter string
	PageOffset      int64
	PageSize        int64
	SortKey         string
	SortDirection   string
	ShowVoided      int64
}

type ListAssetEventsPageRow struct {
	ID                  string
	TenantID            string
	AssetID             string
	TransactionID       string
	EventType           string
	BaseAmountMinor     int64
	BaseCurrency        string
	OriginalAmountMinor sql.NullInt64
	OriginalCurrency    sql.NullString
	FxRateScaled        sql.NullInt64
	FxRateDate          sql.NullString
	FxRateSource        sql.NullString
	Notes               string
	VoidsEventID        sql.NullString
	ReplacesEventID     sql.NullString
	OccurredAt          string
	CreatedByUserID     string
	CreatedAt           string
	IsVoided            bool
	TotalCount          int64
}

func (q *Queries) ListAssetEventsPage(ctx context.Context, arg ListAssetEventsPageParams) ([]ListAssetEventsPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetEventsPage,
		arg.TenantID,
		arg.AssetID,
		arg.SearchQuery,
		arg.EventTypeFilter,
		arg.PageOffset,
		arg.PageSize,
		arg.SortKey,
		arg.SortDirection,
		arg.ShowVoided,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetEventsPageRow
	for rows.Next() {
		var i ListAssetEventsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssetID,
			&i.TransactionID,
			&i.EventType,
			&i.BaseAmountMinor,
			&i.BaseCurrency,
			&i.OriginalAmountMinor,
			&i.OriginalCurrency,
			&i.FxRateScaled,
			&i.FxRateDate,
			&i.FxRateSource,
			&i.Notes,
			&i.VoidsEventID,
			&i.ReplacesEventID,
			&i.OccurredAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.IsVoided,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssets = `-- name: ListAssets :many
SELECT a.id, a.tenant_id, c.id AS category_id, c.name AS category_name,
       c.icon_key AS category_icon,
       m.id AS model_id, m.name AS model_name, v.id AS variant_id,
       v.name AS variant_name, a.display_name, a.serial_number, a.color,
       a.purchase_channel, a.notes, a.created_at
FROM assets a
JOIN product_variants v ON v.tenant_id = a.tenant_id AND v.id = a.variant_id
JOIN product_models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
WHERE a.tenant_id = ?
ORDER BY a.created_at DESC, a.id
`

type ListAssetsRow struct {
	ID              string
	TenantID        string
	CategoryID      string
	CategoryName    string
	CategoryIcon    string
	ModelID         string
	ModelName       string
	VariantID       string
	VariantName     string
	DisplayName     string
	SerialNumber    string
	Color           string
	PurchaseChannel string
	Notes           string
	CreatedAt       string
}

func (q *Queries) ListAssets(ctx context.Context, tenantID string) ([]ListAssetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssets, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsRow
	for rows.Next() {
		var i ListAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.ModelID,
			&i.ModelName,
			&i.VariantID,
			&i.VariantName,
			&i.DisplayName,
			&i.SerialNumber,
			&i.Color,
			&i.PurchaseChannel,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsWithSummary = `-- name: ListAssetsWithSummary :many
WITH effective_events AS (
SELECT e.id, e.tenant_id, e.asset_id, e.transaction_id, e.event_type, e.base_amount_minor, e.base_currency, e.original_amount_minor, e.original_currency, e.fx_rate_scaled, e.fx_rate_date, e.fx_rate_source, e.notes, e.voids_event_id, e.replaces_event_id, e.occurred_at, e.created_by_user_id, e.created_at
FROM asset_events e
WHERE e.tenant_id = ?4
  AND e.event_type != 'void'
  AND NOT EXISTS (
      SELECT 1 FROM asset_events void_event
      WHERE void_event.tenant_id = e.tenant_id AND void_event.voids_event_id = e.id
  )
),
event_rollup AS (
SELECT asset_id,
       SUM(CASE WHEN base_amount_minor < 0 THEN -base_amount_minor ELSE 0 END) AS expense_minor,
       SUM(CASE WHEN base_amount_minor > 0 THEN base_amount_minor ELSE 0 END) AS income_minor,
       SUM(base_amount_minor) AS net_minor,
       MAX(CASE WHEN event_type = 'purchase' THEN 1 ELSE 0 END) AS has_purchase,
       MAX(CASE WHEN event_type = 'sale' THEN 1 ELSE 0 END) AS has_sale
FROM effective_events
GROUP BY asset_id
),
ranked_events AS (
SELECT asset_id, event_type,
       ROW_NUMBER() OVER (PARTITION BY asset_id ORDER BY occurred_at DESC, created_at DESC, id DESC) AS event_rank
FROM effective_events
WHERE event_type IN ('purchase', 'repair', 'sale')
),
asset_rows AS (
SELECT a.id, a.tenant_id, c.id AS category_id, c.name AS category_name,
       c.icon_key AS category_icon,
       m.id AS model_id, m.name AS model_name, v.id AS variant_id,
       v.name AS variant_name, a.display_name, a.serial_number, a.color,
       a.purchase_channel, a.notes, a.created_at,
       CAST(COALESCE(er.expense_minor, 0) AS INTEGER) AS expense_minor,
       CAST(COALESCE(er.income_minor, 0) AS INTEGER) AS income_minor,
       CAST(COALESCE(er.net_minor, 0) AS INTEGER) AS net_minor,
       COALESCE(er.has_purchase, 0) AS has_purchase,
       COALESCE(er.has_sale, 0) AS has_sale,
       COALESCE(re.event_type, '') AS latest_event_type,
       t.base_currency,
       CAST(?5 AS TEXT) AS sort_key,
       CAST(?6 AS TEXT) AS sort_direction
FROM assets a
JOIN product_variants v ON v.tenant_id = a.tenant_id AND v.id = a.variant_id
JOIN product_models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
JOIN tenants t ON t.id = a.tenant_id
LEFT JOIN event_rollup er ON er.asset_id = a.id
LEFT JOIN ranked_events re ON re.asset_id = a.id AND re.event_rank = 1
WHERE a.tenant_id = ?4
  AND (CAST(?7 AS TEXT) = '' OR (
       LOWER(a.display_name) LIKE '%' || LOWER(CAST(?7 AS TEXT)) || '%' OR
       LOWER(a.serial_number) LIKE '%' || LOWER(CAST(?7 AS TEXT)) || '%' OR
       LOWER(a.color) LIKE '%' || LOWER(CAST(?7 AS TEXT)) || '%' OR
       LOWER(a.purchase_channel) LIKE '%' || LOWER(CAST(?7 AS TEXT)) || '%' OR
       LOWER(a.notes) LIKE '%' || LOWER(CAST(?7 AS TEXT)) || '%' OR
       LOWER(m.name) LIKE '%' || LOWER(CAST(?7 AS TEXT)) || '%' OR
       LOWER(v.name) LIKE '%' || LOWER(CAST(?7 AS TEXT)) || '%' OR
       LOWER(c.name) LIKE '%' || LOWER(CAST(?7 AS TEXT)) || '%'
  ))
)
SELECT id, tenant_id, category_id, category_name, category_icon, model_id, model_name,
       variant_id, variant_name, display_name, serial_number, color, purchase_channel, notes, created_at,
       expense_minor, income_minor, net_minor,
       CASE
           WHEN has_sale = 1 THEN 'sold'
           WHEN has_purchase = 1 AND latest_event_type = 'repair' THEN 'repairing'
           WHEN has_purchase = 1 THEN 'active'
           ELSE 'unacquired'
       END AS status,
       base_currency
FROM asset_rows
WHERE CAST(?1 AS TEXT) = '' OR CAST(?1 AS TEXT) = 'all'
   OR (CAST(?1 AS TEXT) = 'sold' AND has_sale = 1)
   OR (CAST(?1 AS TEXT) = 'repairing' AND has_sale = 0 AND has_purchase = 1 AND latest_event_type = 'repair')
   OR (CAST(?1 AS TEXT) = 'active' AND has_sale = 0 AND has_purchase = 1 AND latest_event_type != 'repair')
   OR (CAST(?1 AS TEXT) = 'unacquired' AND has_sale = 0 AND has_purchase = 0)
ORDER BY
  CASE WHEN sort_key = 'name' AND sort_direction = 'asc' THEN LOWER(display_name) END ASC,
  CASE WHEN sort_key = 'name' AND sort_direction = 'desc' THEN LOWER(display_name) END DESC,
  CASE WHEN sort_key = 'model' AND sort_direction = 'asc' THEN LOWER(model_name || ' ' || variant_name) END ASC,
  CASE WHEN sort_key = 'model' AND sort_direction = 'desc' THEN LOWER(model_name || ' ' || variant_name) END DESC,
  CASE WHEN sort_key = 'status' AND sort_direction = 'asc' THEN status END ASC,
  CASE WHEN sort_key = 'status' AND sort_direction = 'desc' THEN status END DESC,
  CASE WHEN sort_key = 'net' AND sort_direction = 'asc' THEN net_minor END ASC,
  CASE WHEN sort_key = 'net' AND sort_direction = 'desc' THEN net_minor END DESC,
  CASE WHEN sort_key = 'cost' AND sort_direction = 'asc' THEN expense_minor END ASC,
  CASE WHEN sort_key = 'cost' AND sort_direction = 'desc' THEN expense_minor END DESC,
  CASE WHEN sort_key = 'created' AND sort_direction = 'asc' THEN created_at END ASC,
  CASE WHEN sort_key = 'created' AND sort_direction = 'desc' THEN created_at END DESC,
  id
LIMIT ?3 OFFSET ?2
`

type ListAssetsWithSummaryParams struct {
	StatusFilter  string
	PageOffset    int64
	PageSize      int64
	TenantID      string
	SortKey       string
	SortDirection string
	SearchQuery   string
}

type ListAssetsWithSummaryRow struct {
	ID              string
	TenantID        string
	CategoryID      string
	CategoryName    string
	CategoryIcon    string
	ModelID         string
	ModelName       string
	VariantID       string
	VariantName     string
	DisplayName     string
	SerialNumber    string
	Color           string
	PurchaseChannel string
	Notes           string
	CreatedAt       string
	ExpenseMinor    int64
	IncomeMinor     int64
	NetMinor        int64
	Status          string
	BaseCurrency    string
}

func (q *Queries) ListAssetsWithSummary(ctx context.Context, arg ListAssetsWithSummaryParams) ([]ListAssetsWithSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsWithSummary,
		arg.StatusFilter,
		arg.PageOffset,
		arg.PageSize,
		arg.TenantID,
		arg.SortKey,
		arg.SortDirection,
		arg.SearchQuery,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsWithSummaryRow
	for rows.Next() {
		var i ListAssetsWithSummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.ModelID,
			&i.ModelName,
			&i.VariantID,
			&i.VariantName,
			&i.DisplayName,
			&i.SerialNumber,
			&i.Color,
			&i.PurchaseChannel,
			&i.Notes,
			&i.CreatedAt,
			&i.ExpenseMinor,
			&i.IncomeMinor,
			&i.NetMinor,
			&i.Status,
			&i.BaseCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, tenant_id, name, icon_key, created_at
FROM item_categories
WHERE tenant_id = ?
ORDER BY name, id
`

type ListCategoriesRow struct {
	ID        string
	TenantID  string
	Name      string
	IconKey   string
	CreatedAt string
}

func (q *Queries) ListCategories(ctx context.Context, tenantID string) ([]ListCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.IconKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT u.id AS user_id, u.username, tm.role, tm.created_at
FROM tenant_memberships tm
JOIN users u ON u.id = tm.user_id
WHERE tm.tenant_id = ?
ORDER BY u.username_normalized
`

type ListMembersRow struct {
	UserID    string
	Username  string
	Role      string
	CreatedAt string
}

func (q *Queries) ListMembers(ctx context.Context, tenantID string) ([]ListMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersPage = `-- name: ListMembersPage :many
WITH list_options AS (
    SELECT CAST(?6 AS TEXT) AS sort_key,
           CAST(?7 AS TEXT) AS sort_direction
)
SELECT u.id AS user_id, u.username, tm.role, tm.created_at, COUNT(*) OVER () AS total_count
FROM tenant_memberships tm
JOIN users u ON u.id = tm.user_id
CROSS JOIN list_options o
WHERE tm.tenant_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR LOWER(u.username) LIKE '%' || LOWER(CAST(?2 AS TEXT)) || '%')
  AND (CAST(?3 AS TEXT) = '' OR tm.role = CAST(?3 AS TEXT))
ORDER BY
  CASE WHEN o.sort_key = 'username' AND o.sort_direction = 'asc' THEN u.username_normalized END ASC,
  CASE WHEN o.sort_key = 'username' AND o.sort_direction = 'desc' THEN u.username_normalized END DESC,
  CASE WHEN o.sort_key = 'role' AND o.sort_direction = 'asc' THEN tm.role END ASC,
  CASE WHEN o.sort_key = 'role' AND o.sort_direction = 'desc' THEN tm.role END DESC,
  CASE WHEN o.sort_key = 'created' AND o.sort_direction = 'asc' THEN tm.created_at END ASC,
  CASE WHEN o.sort_key = 'created' AND o.sort_direction = 'desc' THEN tm.created_at END DESC,
  u.id
LIMIT ?5 OFFSET ?4
`

type ListMembersPageParams struct {
	TenantID      string
	SearchQuery   string
	RoleFilter    string
	PageOffset    int64
	PageSize      int64
	SortKey       string
	SortDirection string
}

type ListMembersPageRow struct {
	UserID     string
	Username   string
	Role       string
	CreatedAt  string
	TotalCount int64
}

func (q *Queries) ListMembersPage(ctx context.Context, arg ListMembersPageParams) ([]ListMembersPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembersPage,
		arg.TenantID,
		arg.SearchQuery,
		arg.RoleFilter,
		arg.PageOffset,
		arg.PageSize,
		arg.SortKey,
		arg.SortDirection,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersPageRow
	for rows.Next() {
		var i ListMembersPageRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Role,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many
SELECT m.id, m.tenant_id, m.category_id, c.name AS category_name, c.icon_key AS category_icon, m.name, m.created_at,
       m.model_3d_store_id, m.model_3d_object_key, m.model_3d_sha256, m.model_3d_size_bytes,
       m.model_3d_source_url, m.model_3d_author, m.model_3d_license, m.model_3d_updated_at
FROM product_models m
JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
WHERE m.tenant_id = ?
ORDER BY c.name, m.name, m.id
`

type ListModelsRow struct {
	ID               string
	TenantID         string
	CategoryID       string
	CategoryName     string
	CategoryIcon     string
	Name             string
	CreatedAt        string
	Model3dStoreID   sql.NullString
	Model3dObjectKey sql.NullString
	Model3dSha256    sql.NullString
	Model3dSizeBytes sql.NullInt64
	Model3dSourceUrl sql.NullString
	Model3dAuthor    sql.NullString
	Model3dLicense   sql.NullString
	Model3dUpdatedAt sql.NullString
}

func (q *Queries) ListModels(ctx context.Context, tenantID string) ([]ListModelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listModels, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelsRow
	for rows.Next() {
		var i ListModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.Name,
			&i.CreatedAt,
			&i.Model3dStoreID,
			&i.Model3dObjectKey,
			&i.Model3dSha256,
			&i.Model3dSizeBytes,
			&i.Model3dSourceUrl,
			&i.Model3dAuthor,
			&i.Model3dLicense,
			&i.Model3dUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsWithVariants = `-- name: ListModelsWithVariants :many
WITH filtered_models AS (
    SELECT m.id, m.tenant_id, m.category_id, c.name AS category_name,
           c.icon_key AS category_icon, m.name, m.created_at,
           m.model_3d_store_id, m.model_3d_object_key, m.model_3d_sha256, m.model_3d_size_bytes,
           m.model_3d_source_url, m.model_3d_author, m.model_3d_license, m.model_3d_updated_at,
           CAST(?1 AS TEXT) AS sort_key,
           CAST(?2 AS TEXT) AS sort_direction
    FROM product_models m
    JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
    WHERE m.tenant_id = ?3
      AND (CAST(?4 AS TEXT) = '' OR
           LOWER(m.name) LIKE '%' || LOWER(CAST(?4 AS TEXT)) || '%' OR
           LOWER(c.name) LIKE '%' || LOWER(CAST(?4 AS TEXT)) || '%')
      AND (CAST(?5 AS TEXT) = '' OR m.category_id = CAST(?5 AS TEXT))
),
paged_models AS (
    SELECT id, tenant_id, category_id, category_name, category_icon, name, created_at, model_3d_store_id, model_3d_object_key, model_3d_sha256, model_3d_size_bytes, model_3d_source_url, model_3d_author, model_3d_license, model_3d_updated_at, sort_key, sort_direction, COUNT(*) OVER () AS total_count,
           ROW_NUMBER() OVER (ORDER BY
             CASE WHEN sort_key = 'category' AND sort_direction = 'asc' THEN LOWER(category_name) END ASC,
             CASE WHEN sort_key = 'category' AND sort_direction = 'desc' THEN LOWER(category_name) END DESC,
             CASE WHEN sort_key = 'name' AND sort_direction = 'asc' THEN LOWER(name) END ASC,
             CASE WHEN sort_key = 'name' AND sort_direction = 'desc' THEN LOWER(name) END DESC,
             CASE WHEN sort_key = 'created' AND sort_direction = 'asc' THEN created_at END ASC,
             CASE WHEN sort_key = 'created' AND sort_direction = 'desc' THEN created_at END DESC,
             LOWER(category_name), LOWER(name), id) AS page_order
    FROM filtered_models
    LIMIT ?7 OFFSET ?6
)
SELECT pm.id, pm.tenant_id, pm.category_id, pm.category_name, pm.category_icon,
       pm.name, pm.created_at,
       pm.model_3d_store_id, pm.model_3d_object_key, pm.model_3d_sha256, pm.model_3d_size_bytes,
       pm.model_3d_source_url, pm.model_3d_author, pm.model_3d_license, pm.model_3d_updated_at,
       pm.total_count, pm.page_order,
       v.id AS variant_id, v.name AS variant_name, v.created_at AS variant_created_at
FROM paged_models pm
LEFT JOIN product_variants v ON v.tenant_id = pm.tenant_id AND v.model_id = pm.id
ORDER BY pm.page_order, LOWER(v.name), v.id
`

type ListModelsWithVariantsParams struct {
	SortKey        string
	SortDirection  string
	TenantID       string
	SearchQuery    string
	CategoryFilter string
	PageOffset     int64
	PageSize       int64
}

type ListModelsWithVariantsRow struct {
	ID               string
	TenantID         string
	CategoryID       string
	CategoryName     string
	CategoryIcon     string
	Name             string
	CreatedAt        string
	Model3dStoreID   sql.NullString
	Model3dObjectKey sql.NullString
	Model3dSha256    sql.NullString
	Model3dSizeBytes sql.NullInt64
	Model3dSourceUrl sql.NullString
	Model3dAuthor    sql.NullString
	Model3dLicense   sql.NullString
	Model3dUpdatedAt sql.NullString
	TotalCount       int64
	PageOrder        interface{}
	VariantID        sql.NullString
	VariantName      sql.NullString
	VariantCreatedAt sql.NullString
}

func (q *Queries) ListModelsWithVariants(ctx context.Context, arg ListModelsWithVariantsParams) ([]ListModelsWithVariantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listModelsWithVariants,
		arg.SortKey,
		arg.SortDirection,
		arg.TenantID,
		arg.SearchQuery,
		arg.CategoryFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelsWithVariantsRow
	for rows.Next() {
		var i ListModelsWithVariantsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.Name,
			&i.CreatedAt,
			&i.Model3dStoreID,
			&i.Model3dObjectKey,
			&i.Model3dSha256,
			&i.Model3dSizeBytes,
			&i.Model3dSourceUrl,
			&i.Model3dAuthor,
			&i.Model3dLicense,
			&i.Model3dUpdatedAt,
			&i.TotalCount,
			&i.PageOrder,
			&i.VariantID,
			&i.VariantName,
			&i.VariantCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariants = `-- name: ListVariants :many
SELECT v.id, v.tenant_id, m.category_id, c.name AS category_name,
       c.icon_key AS category_icon, v.model_id, m.name AS model_name, v.name, v.created_at
FROM product_variants v
JOIN product_models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
JOIN item_categories c ON c.tenant_id = m.tenant_id AND c.id = m.category_id
WHERE v.tenant_id = ?
ORDER BY c.name, m.name, v.name, v.id
`

type ListVariantsRow struct {
	ID           string
	TenantID     string
	CategoryID   string
	CategoryName string
	CategoryIcon string
	ModelID      string
	ModelName    string
	Name         string
	CreatedAt    string
}

func (q *Queries) ListVariants(ctx context.Context, tenantID string) ([]ListVariantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVariants, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVariantsRow
	for rows.Next() {
		var i ListVariantsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.ModelID,
			&i.ModelName,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLifecycleTenant = `-- name: LockLifecycleTenant :execrows
UPDATE tenants SET id = id WHERE id = ?1
`

func (q *Queries) LockLifecycleTenant(ctx context.Context, tenantID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockLifecycleTenant, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const lockTenantBaseCurrency = `-- name: LockTenantBaseCurrency :exec
UPDATE tenants
SET base_currency_locked = 1
WHERE id = ? AND base_currency = ?
`

type LockTenantBaseCurrencyParams struct {
	ID           string
	BaseCurrency string
}

func (q *Queries) LockTenantBaseCurrency(ctx context.Context, arg LockTenantBaseCurrencyParams) error {
	_, err := q.db.ExecContext(ctx, lockTenantBaseCurrency, arg.ID, arg.BaseCurrency)
	return err
}

const saveLifecycleRequest = `-- name: SaveLifecycleRequest :exec
INSERT INTO lifecycle_requests (tenant_id, user_id, request_key, request_hash, event_id)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type SaveLifecycleRequestParams struct {
	TenantID    string
	UserID      string
	RequestKey  string
	RequestHash string
	EventID     string
}

func (q *Queries) SaveLifecycleRequest(ctx context.Context, arg SaveLifecycleRequestParams) error {
	_, err := q.db.ExecContext(ctx, saveLifecycleRequest,
		arg.TenantID,
		arg.UserID,
		arg.RequestKey,
		arg.RequestHash,
		arg.EventID,
	)
	return err
}

const updateCatalogAsset = `-- name: UpdateCatalogAsset :execrows
UPDATE assets
SET variant_id = ?, display_name = ?, serial_number = ?, color = ?, purchase_channel = ?, notes = ?
WHERE tenant_id = ? AND id = ?
`

type UpdateCatalogAssetParams struct {
	VariantID       string
	DisplayName     string
	SerialNumber    string
	Color           string
	PurchaseChannel string
	Notes           string
	TenantID        string
	ID              string
}

func (q *Queries) UpdateCatalogAsset(ctx context.Context, arg UpdateCatalogAssetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCatalogAsset,
		arg.VariantID,
		arg.DisplayName,
		arg.SerialNumber,
		arg.Color,
		arg.PurchaseChannel,
		arg.Notes,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCategory = `-- name: UpdateCategory :execrows
UPDATE item_categories
SET name = ?, icon_key = ?
WHERE tenant_id = ? AND id = ?
`

type UpdateCategoryParams struct {
	Name     string
	IconKey  string
	TenantID string
	ID       string
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCategory,
		arg.Name,
		arg.IconKey,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateModel = `-- name: UpdateModel :execrows
UPDATE product_models
SET category_id = ?, name = ?
WHERE tenant_id = ? AND id = ?
`

type UpdateModelParams struct {
	CategoryID string
	Name       string
	TenantID   string
	ID         string
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateModel,
		arg.CategoryID,
		arg.Name,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProductModel3D = `-- name: UpdateProductModel3D :execrows
UPDATE product_models SET model_3d_store_id = ?, model_3d_object_key = ?, model_3d_sha256 = ?,
 model_3d_size_bytes = ?, model_3d_source_url = ?, model_3d_author = ?, model_3d_license = ?, model_3d_updated_at = ?
WHERE tenant_id = ? AND id = ?
`

type UpdateProductModel3DParams struct {
	Model3dStoreID   sql.NullString
	Model3dObjectKey sql.NullString
	Model3dSha256    sql.NullString
	Model3dSizeBytes sql.NullInt64
	Model3dSourceUrl sql.NullString
	Model3dAuthor    sql.NullString
	Model3dLicense   sql.NullString
	Model3dUpdatedAt sql.NullString
	TenantID         string
	ID               string
}

func (q *Queries) UpdateProductModel3D(ctx context.Context, arg UpdateProductModel3DParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProductModel3D,
		arg.Model3dStoreID,
		arg.Model3dObjectKey,
		arg.Model3dSha256,
		arg.Model3dSizeBytes,
		arg.Model3dSourceUrl,
		arg.Model3dAuthor,
		arg.Model3dLicense,
		arg.Model3dUpdatedAt,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserPreferences = `-- name: UpdateUserPreferences :exec
UPDATE users SET locale = ?, theme = ?, accent = ? WHERE id = ?
`

type UpdateUserPreferencesParams struct {
	Locale string
	Theme  string
	Accent string
	ID     string
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPreferences,
		arg.Locale,
		arg.Theme,
		arg.Accent,
		arg.ID,
	)
	return err
}

const updateVariant = `-- name: UpdateVariant :execrows
UPDATE product_variants
SET model_id = ?, name = ?
WHERE tenant_id = ? AND id = ?
`

type UpdateVariantParams struct {
	ModelID  string
	Name     string
	TenantID string
	ID       string
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVariant,
		arg.ModelID,
		arg.Name,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
