// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: specification.sql

package sqlitedb

import (
	"context"
)

const addAppearanceCondition = `-- name: AddAppearanceCondition :exec
INSERT INTO model_appearance_conditions(tenant_id,rule_id,model_id,tag_id) VALUES(?1,?2,?3,?4)
`

type AddAppearanceConditionParams struct {
	TenantID string
	RuleID   string
	ModelID  string
	TagID    string
}

func (q *Queries) AddAppearanceCondition(ctx context.Context, arg AddAppearanceConditionParams) error {
	_, err := q.db.ExecContext(ctx, addAppearanceCondition,
		arg.TenantID,
		arg.RuleID,
		arg.ModelID,
		arg.TagID,
	)
	return err
}

const addAssetSpecificationTag = `-- name: AddAssetSpecificationTag :exec
INSERT INTO asset_specification_tags(tenant_id,asset_id,model_id,tag_id) VALUES(?1,?2,?3,?4)
`

type AddAssetSpecificationTagParams struct {
	TenantID string
	AssetID  string
	ModelID  string
	TagID    string
}

func (q *Queries) AddAssetSpecificationTag(ctx context.Context, arg AddAssetSpecificationTagParams) error {
	_, err := q.db.ExecContext(ctx, addAssetSpecificationTag,
		arg.TenantID,
		arg.AssetID,
		arg.ModelID,
		arg.TagID,
	)
	return err
}

const addModelAllowedTag = `-- name: AddModelAllowedTag :exec
INSERT INTO model_allowed_tags(tenant_id,model_id,tag_id) VALUES(?1,?2,?3) ON CONFLICT DO NOTHING
`

type AddModelAllowedTagParams struct {
	TenantID string
	ModelID  string
	TagID    string
}

func (q *Queries) AddModelAllowedTag(ctx context.Context, arg AddModelAllowedTagParams) error {
	_, err := q.db.ExecContext(ctx, addModelAllowedTag, arg.TenantID, arg.ModelID, arg.TagID)
	return err
}

const addResourceCategory = `-- name: AddResourceCategory :exec
INSERT INTO resource_categories(tenant_id,resource_id,category_id) VALUES(?1,?2,?3)
`

type AddResourceCategoryParams struct {
	TenantID   string
	ResourceID string
	CategoryID string
}

func (q *Queries) AddResourceCategory(ctx context.Context, arg AddResourceCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addResourceCategory, arg.TenantID, arg.ResourceID, arg.CategoryID)
	return err
}

const addResourceSpecificationTag = `-- name: AddResourceSpecificationTag :exec
INSERT INTO resource_specification_tags(tenant_id,resource_id,tag_id) VALUES(?1,?2,?3)
`

type AddResourceSpecificationTagParams struct {
	TenantID   string
	ResourceID string
	TagID      string
}

func (q *Queries) AddResourceSpecificationTag(ctx context.Context, arg AddResourceSpecificationTagParams) error {
	_, err := q.db.ExecContext(ctx, addResourceSpecificationTag, arg.TenantID, arg.ResourceID, arg.TagID)
	return err
}

const clearAppearanceConditions = `-- name: ClearAppearanceConditions :exec
DELETE FROM model_appearance_conditions WHERE tenant_id=?1 AND rule_id=?2
`

type ClearAppearanceConditionsParams struct {
	TenantID string
	RuleID   string
}

func (q *Queries) ClearAppearanceConditions(ctx context.Context, arg ClearAppearanceConditionsParams) error {
	_, err := q.db.ExecContext(ctx, clearAppearanceConditions, arg.TenantID, arg.RuleID)
	return err
}

const clearAppearanceDimensions = `-- name: ClearAppearanceDimensions :exec
DELETE FROM model_appearance_dimensions WHERE tenant_id=?1 AND model_id=?2
`

type ClearAppearanceDimensionsParams struct {
	TenantID string
	ModelID  string
}

func (q *Queries) ClearAppearanceDimensions(ctx context.Context, arg ClearAppearanceDimensionsParams) error {
	_, err := q.db.ExecContext(ctx, clearAppearanceDimensions, arg.TenantID, arg.ModelID)
	return err
}

const clearAssetSpecificationTags = `-- name: ClearAssetSpecificationTags :exec
DELETE FROM asset_specification_tags WHERE tenant_id=?1 AND asset_id=?2
`

type ClearAssetSpecificationTagsParams struct {
	TenantID string
	AssetID  string
}

func (q *Queries) ClearAssetSpecificationTags(ctx context.Context, arg ClearAssetSpecificationTagsParams) error {
	_, err := q.db.ExecContext(ctx, clearAssetSpecificationTags, arg.TenantID, arg.AssetID)
	return err
}

const clearResourceCategories = `-- name: ClearResourceCategories :exec
DELETE FROM resource_categories WHERE tenant_id=?1 AND resource_id=?2
`

type ClearResourceCategoriesParams struct {
	TenantID   string
	ResourceID string
}

func (q *Queries) ClearResourceCategories(ctx context.Context, arg ClearResourceCategoriesParams) error {
	_, err := q.db.ExecContext(ctx, clearResourceCategories, arg.TenantID, arg.ResourceID)
	return err
}

const clearResourceSpecificationTags = `-- name: ClearResourceSpecificationTags :exec
DELETE FROM resource_specification_tags WHERE tenant_id=?1 AND resource_id=?2
`

type ClearResourceSpecificationTagsParams struct {
	TenantID   string
	ResourceID string
}

func (q *Queries) ClearResourceSpecificationTags(ctx context.Context, arg ClearResourceSpecificationTagsParams) error {
	_, err := q.db.ExecContext(ctx, clearResourceSpecificationTags, arg.TenantID, arg.ResourceID)
	return err
}

const createSelectedAsset = `-- name: CreateSelectedAsset :exec
INSERT INTO assets(id,tenant_id,model_id,display_name,serial_number,purchase_channel,notes,created_at)
VALUES(?1,?2,?3,?4,?5,?6,?7,?8)
`

type CreateSelectedAssetParams struct {
	ID              string
	TenantID        string
	ModelID         string
	DisplayName     string
	SerialNumber    string
	PurchaseChannel string
	Notes           string
	CreatedAt       string
}

func (q *Queries) CreateSelectedAsset(ctx context.Context, arg CreateSelectedAssetParams) error {
	_, err := q.db.ExecContext(ctx, createSelectedAsset,
		arg.ID,
		arg.TenantID,
		arg.ModelID,
		arg.DisplayName,
		arg.SerialNumber,
		arg.PurchaseChannel,
		arg.Notes,
		arg.CreatedAt,
	)
	return err
}

const deleteAppearanceDefault = `-- name: DeleteAppearanceDefault :exec
DELETE FROM model_appearance_defaults WHERE tenant_id=?1 AND id=?2
`

type DeleteAppearanceDefaultParams struct {
	TenantID string
	ID       string
}

func (q *Queries) DeleteAppearanceDefault(ctx context.Context, arg DeleteAppearanceDefaultParams) error {
	_, err := q.db.ExecContext(ctx, deleteAppearanceDefault, arg.TenantID, arg.ID)
	return err
}

const putAppearanceDefault = `-- name: PutAppearanceDefault :exec
INSERT INTO model_appearance_defaults(id,tenant_id,model_id,resource_id,created_at,updated_at)
VALUES(?1,?2,?3,?4,?5,?6)
ON CONFLICT(tenant_id,id) DO UPDATE SET resource_id=excluded.resource_id,updated_at=excluded.updated_at
`

type PutAppearanceDefaultParams struct {
	ID         string
	TenantID   string
	ModelID    string
	ResourceID string
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) PutAppearanceDefault(ctx context.Context, arg PutAppearanceDefaultParams) error {
	_, err := q.db.ExecContext(ctx, putAppearanceDefault,
		arg.ID,
		arg.TenantID,
		arg.ModelID,
		arg.ResourceID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const putAppearanceDimension = `-- name: PutAppearanceDimension :exec
INSERT INTO model_appearance_dimensions(tenant_id,model_id,type_id,affects_appearance) VALUES(?1,?2,?3,?4)
`

type PutAppearanceDimensionParams struct {
	TenantID          string
	ModelID           string
	TypeID            string
	AffectsAppearance int64
}

func (q *Queries) PutAppearanceDimension(ctx context.Context, arg PutAppearanceDimensionParams) error {
	_, err := q.db.ExecContext(ctx, putAppearanceDimension,
		arg.TenantID,
		arg.ModelID,
		arg.TypeID,
		arg.AffectsAppearance,
	)
	return err
}

const putSpecificationTag = `-- name: PutSpecificationTag :exec
INSERT INTO specification_tags(id,tenant_id,type_id,name,normalized_name,enabled,created_at,updated_at)
VALUES(?1,?2,?3,?4,?5,?6,?7,?8)
ON CONFLICT(tenant_id,id) DO UPDATE SET name=excluded.name,normalized_name=excluded.normalized_name,enabled=excluded.enabled,updated_at=excluded.updated_at
`

type PutSpecificationTagParams struct {
	ID             string
	TenantID       string
	TypeID         string
	Name           string
	NormalizedName string
	Enabled        int64
	CreatedAt      string
	UpdatedAt      string
}

func (q *Queries) PutSpecificationTag(ctx context.Context, arg PutSpecificationTagParams) error {
	_, err := q.db.ExecContext(ctx, putSpecificationTag,
		arg.ID,
		arg.TenantID,
		arg.TypeID,
		arg.Name,
		arg.NormalizedName,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const putSpecificationType = `-- name: PutSpecificationType :exec
INSERT INTO specification_tag_types(id,tenant_id,name,normalized_name,multiple,affects_appearance,enabled,system_code,created_at,updated_at)
VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10)
ON CONFLICT(tenant_id,id) DO UPDATE SET name=excluded.name,normalized_name=excluded.normalized_name,multiple=excluded.multiple,affects_appearance=excluded.affects_appearance,enabled=excluded.enabled,updated_at=excluded.updated_at
`

type PutSpecificationTypeParams struct {
	ID                string
	TenantID          string
	Name              string
	NormalizedName    string
	Multiple          int64
	AffectsAppearance int64
	Enabled           int64
	SystemCode        string
	CreatedAt         string
	UpdatedAt         string
}

func (q *Queries) PutSpecificationType(ctx context.Context, arg PutSpecificationTypeParams) error {
	_, err := q.db.ExecContext(ctx, putSpecificationType,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.NormalizedName,
		arg.Multiple,
		arg.AffectsAppearance,
		arg.Enabled,
		arg.SystemCode,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const removeModelAllowedTag = `-- name: RemoveModelAllowedTag :exec
DELETE FROM model_allowed_tags WHERE tenant_id=?1 AND model_id=?2 AND tag_id=?3
`

type RemoveModelAllowedTagParams struct {
	TenantID string
	ModelID  string
	TagID    string
}

func (q *Queries) RemoveModelAllowedTag(ctx context.Context, arg RemoveModelAllowedTagParams) error {
	_, err := q.db.ExecContext(ctx, removeModelAllowedTag, arg.TenantID, arg.ModelID, arg.TagID)
	return err
}

const resolveLegacyMedia = `-- name: ResolveLegacyMedia :execrows
UPDATE legacy_variant_media SET resolved=1 WHERE tenant_id=?1 AND variant_id=?2
`

type ResolveLegacyMediaParams struct {
	TenantID  string
	VariantID string
}

func (q *Queries) ResolveLegacyMedia(ctx context.Context, arg ResolveLegacyMediaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveLegacyMedia, arg.TenantID, arg.VariantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const specificationCategories = `-- name: SpecificationCategories :many
SELECT CAST(id AS TEXT) AS id FROM item_categories WHERE tenant_id=?1
`

func (q *Queries) SpecificationCategories(ctx context.Context, tenantID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, specificationCategories, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const specificationDefaults = `-- name: SpecificationDefaults :many
SELECT CAST(id AS TEXT) AS id,CAST(model_id AS TEXT) AS model_id,CAST(resource_id AS TEXT) AS resource_id FROM model_appearance_defaults WHERE tenant_id=?1 ORDER BY id
`

type SpecificationDefaultsRow struct {
	ID         string
	ModelID    string
	ResourceID string
}

func (q *Queries) SpecificationDefaults(ctx context.Context, tenantID string) ([]SpecificationDefaultsRow, error) {
	rows, err := q.db.QueryContext(ctx, specificationDefaults, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpecificationDefaultsRow
	for rows.Next() {
		var i SpecificationDefaultsRow
		if err := rows.Scan(&i.ID, &i.ModelID, &i.ResourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const specificationDimensions = `-- name: SpecificationDimensions :many
SELECT CAST(model_id AS TEXT) AS model_id,CAST(type_id AS TEXT) AS type_id,affects_appearance FROM model_appearance_dimensions WHERE tenant_id=?1
`

type SpecificationDimensionsRow struct {
	ModelID           string
	TypeID            string
	AffectsAppearance int64
}

func (q *Queries) SpecificationDimensions(ctx context.Context, tenantID string) ([]SpecificationDimensionsRow, error) {
	rows, err := q.db.QueryContext(ctx, specificationDimensions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpecificationDimensionsRow
	for rows.Next() {
		var i SpecificationDimensionsRow
		if err := rows.Scan(&i.ModelID, &i.TypeID, &i.AffectsAppearance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const specificationLegacyMedia = `-- name: SpecificationLegacyMedia :many
SELECT CAST(variant_id AS TEXT) AS variant_id,CAST(model_id AS TEXT) AS model_id,CAST(resource_id AS TEXT) AS resource_id,reason,resolved FROM legacy_variant_media WHERE tenant_id=?1
`

type SpecificationLegacyMediaRow struct {
	VariantID  string
	ModelID    string
	ResourceID string
	Reason     string
	Resolved   int64
}

func (q *Queries) SpecificationLegacyMedia(ctx context.Context, tenantID string) ([]SpecificationLegacyMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, specificationLegacyMedia, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpecificationLegacyMediaRow
	for rows.Next() {
		var i SpecificationLegacyMediaRow
		if err := rows.Scan(
			&i.VariantID,
			&i.ModelID,
			&i.ResourceID,
			&i.Reason,
			&i.Resolved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const specificationLinks = `-- name: SpecificationLinks :many
SELECT CAST('model' AS TEXT) AS kind,CAST(mt.model_id AS TEXT) AS target_id,CAST(mt.model_id AS TEXT) AS model_id,CAST(mt.tag_id AS TEXT) AS tag_id FROM model_allowed_tags mt WHERE mt.tenant_id=?1
UNION ALL SELECT 'asset',CAST(at.asset_id AS TEXT),CAST(at.model_id AS TEXT),CAST(at.tag_id AS TEXT) FROM asset_specification_tags at WHERE at.tenant_id=?1
UNION ALL SELECT 'resource',CAST(rt.resource_id AS TEXT),'',CAST(rt.tag_id AS TEXT) FROM resource_specification_tags rt WHERE rt.tenant_id=?1
UNION ALL SELECT 'resource-category',CAST(rc.resource_id AS TEXT),'',CAST(rc.category_id AS TEXT) FROM resource_categories rc WHERE rc.tenant_id=?1
UNION ALL SELECT 'appearance',CAST(ac.rule_id AS TEXT),CAST(ac.model_id AS TEXT),CAST(ac.tag_id AS TEXT) FROM model_appearance_conditions ac WHERE ac.tenant_id=?1
UNION ALL SELECT 'legacy',CAST(l.variant_id AS TEXT),CAST(v.model_id AS TEXT),CAST(l.tag_id AS TEXT) FROM legacy_variant_tags l JOIN product_variants v ON v.tenant_id=l.tenant_id AND v.id=l.variant_id WHERE l.tenant_id=?1
`

type SpecificationLinksRow struct {
	Kind     string
	TargetID string
	ModelID  string
	TagID    string
}

func (q *Queries) SpecificationLinks(ctx context.Context, tenantID string) ([]SpecificationLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, specificationLinks, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpecificationLinksRow
	for rows.Next() {
		var i SpecificationLinksRow
		if err := rows.Scan(
			&i.Kind,
			&i.TargetID,
			&i.ModelID,
			&i.TagID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const specificationTags = `-- name: SpecificationTags :many
SELECT CAST(id AS TEXT) AS id,CAST(type_id AS TEXT) AS type_id,name,normalized_name,enabled,created_at,updated_at
FROM specification_tags WHERE tenant_id=?1 ORDER BY type_id,normalized_name,id
`

type SpecificationTagsRow struct {
	ID             string
	TypeID         string
	Name           string
	NormalizedName string
	Enabled        int64
	CreatedAt      string
	UpdatedAt      string
}

func (q *Queries) SpecificationTags(ctx context.Context, tenantID string) ([]SpecificationTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, specificationTags, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpecificationTagsRow
	for rows.Next() {
		var i SpecificationTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.TypeID,
			&i.Name,
			&i.NormalizedName,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const specificationTypes = `-- name: SpecificationTypes :many
SELECT CAST(id AS TEXT) AS id,name,normalized_name,multiple,affects_appearance,enabled,system_code,created_at,updated_at
FROM specification_tag_types WHERE tenant_id=?1 ORDER BY normalized_name,id
`

type SpecificationTypesRow struct {
	ID                string
	Name              string
	NormalizedName    string
	Multiple          int64
	AffectsAppearance int64
	Enabled           int64
	SystemCode        string
	CreatedAt         string
	UpdatedAt         string
}

func (q *Queries) SpecificationTypes(ctx context.Context, tenantID string) ([]SpecificationTypesRow, error) {
	rows, err := q.db.QueryContext(ctx, specificationTypes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpecificationTypesRow
	for rows.Next() {
		var i SpecificationTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.Multiple,
			&i.AffectsAppearance,
			&i.Enabled,
			&i.SystemCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSelectedAsset = `-- name: UpdateSelectedAsset :execrows
UPDATE assets SET model_id=?1,display_name=?2,serial_number=?3,purchase_channel=?4,notes=?5
WHERE tenant_id=?6 AND id=?7
`

type UpdateSelectedAssetParams struct {
	ModelID         string
	DisplayName     string
	SerialNumber    string
	PurchaseChannel string
	Notes           string
	TenantID        string
	ID              string
}

func (q *Queries) UpdateSelectedAsset(ctx context.Context, arg UpdateSelectedAssetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSelectedAsset,
		arg.ModelID,
		arg.DisplayName,
		arg.SerialNumber,
		arg.PurchaseChannel,
		arg.Notes,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
